BASE_ITEM_ID = 9901000


ITEM_MAPPING = {
	[1] = {{ "ruby", "toggle" }},
	[2] = {{ "sapphire", "toggle" }},
	[3] = {{ "startball", "consumable" }},
	[4] = {{ "startcoins", "progressive" }},
	[5] = {{"startballplus", "consumable" }},
	[6] = {{ "perpichu", "toggle" }},
	[7] = {{ "guest", "toggle" }},
	[8] = {{ "ratecard", "toggle" }},
	[9] = {{ "ruinscard", "toggle" }},
	[10] ={ { "get", "progressive" }},
	[11] = {{ "evo", "progressive" } },
	[13] = {{ "chiko", "toggle" }},
	[14] = {{ "cynda", "toggle" }},
	[15] = {{ "toto", "toggle" }},
	[16] = {{ "aero", "toggle" }},
	[17] = {{ "egg1", "toggle" }},
	[18] = {{ "egg2", "toggle" }},
	[19] = {{ "egg3", "toggle" }},
	[20] = {{ "egg4", "toggle" }},
	[21] = {{ "eggruby", "toggle" }},
	[22] = {{ "eggsapphire", "toggle" }},
	[256] = {{ "forestR", "toggle" }},
	[257] = { {"volcanoR", "toggle" }},
	[258] = { {"plainsR", "toggle" }},
	[259] = {{ "oceanR", "toggle" }},
	[260] = {{ "safariR", "toggle" }},
	[261] = {{ "caveR", "toggle" }},
	[262] = {{ "ruinsR", "toggle" }},
	[263] = {{ "forestS", "toggle" }},
	[264] = {{ "lakeS", "toggle" }},
	[265] = {{ "plainsS", "toggle" }},
	[266] = {{ "wildernessS", "toggle" }},
	[267] = {{ "oceanS", "toggle" }},
	[268] = {{ "caveS", "toggle" }},
	[269] = {{ "ruinsS", "toggle" }},
	[512] = {{ "filler", "toggle" }},
	[513] = {{ "filler", "toggle" }},
	[514] = {{ "filler", "toggle" }},
	[515] = {{ "filler", "toggle" }},

}
