BASE_ITEM_ID = 9901000


ITEM_MAPPING = {
	[1] = { { "ruby", "toggle" } },
	[2] = { { "sapphire", "toggle" } },
	[3] = { { "startball", "consumable" } },
	[4] = { { "startcoins", "progressive" } },
	[5] = { { "startballplus", "progressive" } },
	[6] = { { "perpichu", "toggle" } },
	[7] = { { "guest", "toggle" } },
	[8] = { { "ratecard", "toggle" } },
	[9] = { { "ruinscard", "toggle" } },
	[10] = { { "get", "progressive" } },
	[11] = { { "evo", "progressive" } },
	[12] = { { "evomode", "toggle" } },
	[13] = { { "chiko", "toggle" } },
	[14] = { { "cynda", "toggle" } },
	[15] = { { "toto", "toggle" } },
	[16] = { { "aero", "toggle" } },
	[17] = { { "eggfor", "toggle" } },
	[18] = { { "eggcave", "toggle" } },
	[19] = { { "eggmon", "toggle" } },
	[20] = { { "eggdes", "toggle" } },
	[21] = { { "eggsea", "toggle" } },
	[22] = { { "eggruby", "toggle" } },
	[23] = { { "eggsapphire", "toggle" } },
	[24] = { { "coin", "progressive" } },
	[25] = { { "doublecoin", "toggle" } },
	[26] = { { "medals", "consumable" } },
	[256] = { { "forestR", "toggle" } },
	[257] = { { "volcanoR", "toggle" } },
	[258] = { { "plainsR", "toggle" } },
	[259] = { { "oceanR", "toggle" } },
	[260] = { { "safariR", "toggle" } },
	[261] = { { "caveR", "toggle" } },
	[262] = { { "ruinsR", "toggle" } },
	[263] = { { "forestS", "toggle" } },
	[264] = { { "lakeS", "toggle" } },
	[265] = { { "plainsS", "toggle" } },
	[266] = { { "wildernessS", "toggle" } },
	[267] = { { "oceanS", "toggle" } },
	[268] = { { "caveS", "toggle" } },
	[269] = { { "ruinsS", "toggle" } },
	[512] = { { "filler", "toggle" } },
	[513] = { { "filler", "toggle" } },
	[514] = { { "filler", "toggle" } },
	[515] = { { "filler", "toggle" } },
	[1025] = { { "exp", "toggle" } },
	[1026] = { { "leaf", "toggle" } },
	[1027] = { { "fire", "toggle" } },
	[1028] = { { "link", "toggle" } },
	[1029] = { { "moon", "toggle" } },
	[1030] = { { "water", "toggle" } },
	[1031] = { { "thunder", "toggle" } },
	[1032] = { { "sun", "toggle" } },
	[1033] = { { "friend", "toggle" } },
	[1034] = { { "block", "toggle" } },
	[2048] = { { "bonuszig", "toggle" } },
	[2049] = { { "bonuspel", "toggle" } },
	[2050] = { { "bonusmak", "toggle" } },
	[2051] = { { "bonuswhis", "toggle" } },



}
