HIGHLIGHT_STATUS_MAPPING = {
    [0] = 2,   --Unspecified
    [10] = 1,  -- NoPriority
    [20] = -1, -- Avoid
    [30] = 3,  -- Priority
    [40] = 0   -- None
}

Pokemon = {
    [1] = "Treecko",
    [2] = "Grovyle",
    [3] = "Sceptile",
    [4] = "Torchic",
    [5] = "Combusken",
    [6] = "Blaziken",
    [7] = "Mudkip",
    [8] = "Marshtomp",
    [9] = "Swampert",
    [10] = "Poochyena",
    [11] = "Mightyena",
    [12] = "Zigzagoon",
    [13] = "Linoone",
    [14] = "Wurmple",
    [15] = "Silcoon",
    [16] = "Beautifly",
    [17] = "Cascoon",
    [18] = "Dustox",
    [19] = "Lotad",
    [20] = "Lombre",
    [21] = "Ludicolo",
    [22] = "Seedot",
    [23] = "Nuzleaf",
    [24] = "Shiftry",
    [25] = "Taillow",
    [26] = "Swellow",
    [27] = "Wingull",
    [28] = "Pelipper",
    [29] = "Ralts",
    [30] = "Kirlia",
    [31] = "Gardevoir",
    [32] = "Surskit",
    [33] = "Masquerain",
    [34] = "Shroomish",
    [35] = "Breloom",
    [36] = "Slakoth",
    [37] = "Vigoroth",
    [38] = "Slaking",
    [39] = "Abra",
    [40] = "Kadabra",
    [41] = "Alakazam",
    [42] = "Nincada",
    [43] = "Ninjask",
    [44] = "Shedinja",
    [45] = "Whismur",
    [46] = "Loudred",
    [47] = "Exploud",
    [48] = "Makuhita",
    [49] = "Hariyama",
    [50] = "Goldeen",
    [51] = "Seaking",
    [52] = "Magikarp",
    [53] = "Gyarados",
    [54] = "Azurill",
    [55] = "Marill",
    [56] = "Azumarill",
    [57] = "Geodude",
    [58] = "Graveler",
    [59] = "Golem",
    [60] = "Nosepass",
    [61] = "Skitty",
    [62] = "Delcatty",
    [63] = "Zubat",
    [64] = "Golbat",
    [65] = "Crobat",
    [66] = "Tentacool",
    [67] = "Tentacruel",
    [68] = "Sableye",
    [69] = "Mawile",
    [70] = "Aron",
    [71] = "Lairon",
    [72] = "Aggron",
    [73] = "Machop",
    [74] = "Machoke",
    [75] = "Machamp",
    [76] = "Meditite",
    [77] = "Medicham",
    [78] = "Electrike",
    [79] = "Manectric",
    [80] = "Plusle",
    [81] = "Minun",
    [82] = "Magnemite",
    [83] = "Magneton",
    [84] = "Voltorb",
    [85] = "Electrode",
    [86] = "Volbeat",
    [87] = "Illumise",
    [88] = "Oddish",
    [89] = "Gloom",
    [90] = "Vileplume",
    [91] = "Bellossom",
    [92] = "Doduo",
    [93] = "Dodrio",
    [94] = "Roselia",
    [95] = "Gulpin",
    [96] = "Swalot",
    [97] = "Carvanha",
    [98] = "Sharpedo",
    [99] = "Wailmer",
    [100] = "Wailord",
    [101] = "Numel",
    [102] = "Camerupt",
    [103] = "Slugma",
    [104] = "Magcargo",
    [105] = "Torkoal",
    [106] = "Grimer",
    [107] = "Muk",
    [108] = "Koffing",
    [109] = "Weezing",
    [110] = "Spoink",
    [111] = "Grumpig",
    [112] = "Sandshrew",
    [113] = "Sandslash",
    [114] = "Spinda",
    [115] = "Skarmory",
    [116] = "Trapinch",
    [117] = "Vibrava",
    [118] = "Flygon",
    [119] = "Cacnea",
    [120] = "Cacturne",
    [121] = "Swablu",
    [122] = "Altaria",
    [123] = "Zangoose",
    [124] = "Seviper",
    [125] = "Lunatone",
    [126] = "Solrock",
    [127] = "Barboach",
    [128] = "Whiscash",
    [129] = "Corphish",
    [130] = "Crawdaunt",
    [131] = "Baltoy",
    [132] = "Claydol",
    [133] = "Lileep",
    [134] = "Cradily",
    [135] = "Anorith",
    [136] = "Armaldo",
    [137] = "Igglybuff",
    [138] = "Jigglypuff",
    [139] = "Wigglytuff",
    [140] = "Feebas",
    [141] = "Milotic",
    [142] = "Castform",
    [143] = "Staryu",
    [144] = "Starmie",
    [145] = "Kecleon",
    [146] = "Shuppet",
    [147] = "Banette",
    [148] = "Duskull",
    [149] = "Dusclops",
    [150] = "Tropius",
    [151] = "Chimecho",
    [152] = "Absol",
    [153] = "Vulpix",
    [154] = "Ninetales",
    [155] = "Pichu",
    [156] = "Pikachu",
    [157] = "Raichu",
    [158] = "Psyduck",
    [159] = "Golduck",
    [160] = "Wynaut",
    [161] = "Wobbuffet",
    [162] = "Natu",
    [163] = "Xatu",
    [164] = "Girafarig",
    [165] = "Phanpy",
    [166] = "Donphan",
    [167] = "Pinsir",
    [168] = "Heracross",
    [169] = "Rhyhorn",
    [170] = "Rhydon",
    [171] = "Snorunt",
    [172] = "Glalie",
    [173] = "Spheal",
    [174] = "Sealeo",
    [175] = "Walrein",
    [176] = "Clamperl",
    [177] = "Huntail",
    [178] = "Gorebyss",
    [179] = "Relicanth",
    [180] = "Corsola",
    [181] = "Chinchou",
    [182] = "Lanturn",
    [183] = "Luvdisc",
    [184] = "Horsea",
    [185] = "Seadra",
    [186] = "Kingdra",
    [187] = "Bagon",
    [188] = "Shelgon",
    [189] = "Salamence",
    [190] = "Beldum",
    [191] = "Metang",
    [192] = "Metagross",
    [193] = "Regirock",
    [194] = "Regice",
    [195] = "Registeel",
    [196] = "Latias",
    [197] = "Latios",
    [198] = "Kyogre",
    [199] = "Groudon",
    [200] = "Rayquaza",
    [201] = "Jirachi",
    [202] = "Chikorita",
    [203] = "Cyndaquil",
    [204] = "Totodile",
    [205] = "Aerodactyl"


}


PokemonZero = {
    [0] = "Treecko",
    [1] = "Grovyle",
    [2] = "Sceptile",
    [3] = "Torchic",
    [4] = "Combusken",
    [5] = "Blaziken",
    [6] = "Mudkip",
    [7] = "Marshtomp",
    [8] = "Swampert",
    [9] = "Poochyena",
    [10] = "Mightyena",
    [11] = "Zigzagoon",
    [12] = "Linoone",
    [13] = "Wurmple",
    [14] = "Silcoon",
    [15] = "Beautifly",
    [16] = "Cascoon",
    [17] = "Dustox",
    [18] = "Lotad",
    [19] = "Lombre",
    [20] = "Ludicolo",
    [21] = "Seedot",
    [22] = "Nuzleaf",
    [23] = "Shiftry",
    [24] = "Taillow",
    [25] = "Swellow",
    [26] = "Wingull",
    [27] = "Pelipper",
    [28] = "Ralts",
    [29] = "Kirlia",
    [30] = "Gardevoir",
    [31] = "Surskit",
    [32] = "Masquerain",
    [33] = "Shroomish",
    [34] = "Breloom",
    [35] = "Slakoth",
    [36] = "Vigoroth",
    [37] = "Slaking",
    [38] = "Abra",
    [39] = "Kadabra",
    [40] = "Alakazam",
    [41] = "Nincada",
    [42] = "Ninjask",
    [43] = "Shedinja",
    [44] = "Whismur",
    [45] = "Loudred",
    [46] = "Exploud",
    [47] = "Makuhita",
    [48] = "Hariyama",
    [49] = "Goldeen",
    [50] = "Seaking",
    [51] = "Magikarp",
    [52] = "Gyarados",
    [53] = "Azurill",
    [54] = "Marill",
    [55] = "Azumarill",
    [56] = "Geodude",
    [57] = "Graveler",
    [58] = "Golem",
    [59] = "Nosepass",
    [60] = "Skitty",
    [61] = "Delcatty",
    [62] = "Zubat",
    [63] = "Golbat",
    [64] = "Crobat",
    [65] = "Tentacool",
    [66] = "Tentacruel",
    [67] = "Sableye",
    [68] = "Mawile",
    [69] = "Aron",
    [70] = "Lairon",
    [71] = "Aggron",
    [72] = "Machop",
    [73] = "Machoke",
    [74] = "Machamp",
    [75] = "Meditite",
    [76] = "Medicham",
    [77] = "Electrike",
    [78] = "Manectric",
    [79] = "Plusle",
    [80] = "Minun",
    [81] = "Magnemite",
    [82] = "Magneton",
    [83] = "Voltorb",
    [84] = "Electrode",
    [85] = "Volbeat",
    [86] = "Illumise",
    [87] = "Oddish",
    [88] = "Gloom",
    [89] = "Vileplume",
    [90] = "Bellossom",
    [91] = "Doduo",
    [92] = "Dodrio",
    [93] = "Roselia",
    [94] = "Gulpin",
    [95] = "Swalot",
    [96] = "Carvanha",
    [97] = "Sharpedo",
    [98] = "Wailmer",
    [99] = "Wailord",
    [100] = "Numel",
    [101] = "Camerupt",
    [102] = "Slugma",
    [103] = "Magcargo",
    [104] = "Torkoal",
    [105] = "Grimer",
    [106] = "Muk",
    [107] = "Koffing",
    [108] = "Weezing",
    [109] = "Spoink",
    [110] = "Grumpig",
    [111] = "Sandshrew",
    [112] = "Sandslash",
    [113] = "Spinda",
    [114] = "Skarmory",
    [115] = "Trapinch",
    [116] = "Vibrava",
    [117] = "Flygon",
    [118] = "Cacnea",
    [119] = "Cacturne",
    [120] = "Swablu",
    [121] = "Altaria",
    [122] = "Zangoose",
    [123] = "Seviper",
    [124] = "Lunatone",
    [125] = "Solrock",
    [126] = "Barboach",
    [127] = "Whiscash",
    [128] = "Corphish",
    [129] = "Crawdaunt",
    [130] = "Baltoy",
    [131] = "Claydol",
    [132] = "Lileep",
    [133] = "Cradily",
    [134] = "Anorith",
    [135] = "Armaldo",
    [136] = "Igglybuff",
    [137] = "Jigglypuff",
    [138] = "Wigglytuff",
    [139] = "Feebas",
    [140] = "Milotic",
    [141] = "Castform",
    [142] = "Staryu",
    [143] = "Starmie",
    [144] = "Kecleon",
    [145] = "Shuppet",
    [146] = "Banette",
    [147] = "Duskull",
    [148] = "Dusclops",
    [149] = "Tropius",
    [150] = "Chimecho",
    [151] = "Absol",
    [152] = "Vulpix",
    [153] = "Ninetales",
    [154] = "Pichu",
    [155] = "Pikachu",
    [156] = "Raichu",
    [157] = "Psyduck",
    [158] = "Golduck",
    [159] = "Wynaut",
    [160] = "Wobbuffet",
    [161] = "Natu",
    [162] = "Xatu",
    [163] = "Girafarig",
    [164] = "Phanpy",
    [165] = "Donphan",
    [166] = "Pinsir",
    [167] = "Heracross",
    [168] = "Rhyhorn",
    [169] = "Rhydon",
    [170] = "Snorunt",
    [171] = "Glalie",
    [172] = "Spheal",
    [173] = "Sealeo",
    [174] = "Walrein",
    [175] = "Clamperl",
    [176] = "Huntail",
    [177] = "Gorebyss",
    [178] = "Relicanth",
    [179] = "Corsola",
    [180] = "Chinchou",
    [181] = "Lanturn",
    [182] = "Luvdisc",
    [183] = "Horsea",
    [184] = "Seadra",
    [185] = "Kingdra",
    [186] = "Bagon",
    [187] = "Shelgon",
    [188] = "Salamence",
    [189] = "Beldum",
    [190] = "Metang",
    [191] = "Metagross",
    [192] = "Regirock",
    [193] = "Regice",
    [194] = "Registeel",
    [195] = "Latias",
    [196] = "Latios",
    [197] = "Kyogre",
    [198] = "Groudon",
    [199] = "Rayquaza",
    [200] = "Jirachi",
    [201] = "Chikorita",
    [202] = "Cyndaquil",
    [203] = "Totodile",
    [204] = "Aerodactyl"

}


AREAS = {
    {
        { 22,  2 },
        { 11,  2 },
        { 14,  2 },
        { 16,  2 },
        { 147, 2 },
        { 144, 2 },
        { 0,   3 },
        { 41,  3 }
    },
    {
        { 102, 2 },
        { 152, 2 },
        { 104, 2 },
        { 100, 2 },
        { 107, 2 },
        { 114, 2 },
        { 3,   3 }
    },
    {
        { 86,  2 },
        { 77,  2 },
        { 9,   2 },
        { 81,  2 },
        { 83,  2 },
        { 24,  2 },
        { 141, 2 },
        { 122, 3 }
    },
    {
        { 98,  2 },
        { 26,  2 },
        { 65,  2 },
        { 96,  2 },
        { 182, 2 },
        { 132, 2 },
        { 142, 3 },
        { 178, 3 }
    },
    {
        { 157, 2 },
        { 167, 2 },
        { 163, 2 },
        { 166, 2 },
        { 168, 2 },
        { 91,  2 },
        { 160, 2 },
        { 155, 3 }
    },
    {
        { 125, 2 },
        { 68,  2 },
        { 72,  2 },
        { 105, 2 },
        { 187, 2 },
        { 45,  2 },
        { 59,  2 },
        { 38,  3 }
    },
    {
        { 189, 2 },
        { 192, 2 },
        { 193, 2 },
        { 194, 3 },
        { 200, 2 }
    },
    {
        { 35,  2 },
        { 93,  2 },
        { 14,  2 },
        { 16,  2 },
        { 147, 2 },
        { 144, 2 },
        { 149, 3 },
        { 41,  3 }
    },
    {
        { 49,  2 },
        { 54,  2 },
        { 19,  2 },
        { 126, 2 },
        { 128, 2 },
        { 139, 2 },
        { 6,   3 }
    },
    {
        { 137, 2 },
        { 77,  2 },
        { 9,   2 },
        { 81,  2 },
        { 83,  2 },
        { 24,  2 },
        { 141, 2 },
        { 85,  3 },
        { 123, 3 }
    },
    {
        { 130, 2 },
        { 75,  2 },
        { 116, 2 },
        { 118, 2 },
        { 56,  2 },
        { 151, 2 },
        { 120, 3 }
    },
    {
        { 51,  2 },
        { 26,  2 },
        { 65,  2 },
        { 96,  2 },
        { 182, 2 },
        { 134, 2 },
        { 175, 3 },
        { 178, 3 }
    },
    {
        { 124, 2 },
        { 67,  3 },
        { 47,  2 },
        { 105, 2 },
        { 187, 2 },
        { 45,  2 },
        { 59,  2 },
        { 38,  3 }
    },
    {
        { 189, 2 },
        { 192, 2 },
        { 193, 2 },
        { 194, 3 },
        { 200, 2 }
    },

}

SPECIES = {
    ["Wurmple"] = { "Wurmple", "Silcoon", "Beautifly" },
    ["Wurmple "] = { "Wurmple", "Silcoon", "Dustox" },
    ["Ralts"] = { "Ralts", "Kirlia", "Gardevoir" },
    ["Whismur"] = { "Whismur", "Loudred", "Exploud" },
    ["Zubat"] = { "Zubat", "Golbat", "Crobat" },
    ["Aron"] = { "Aron", "Lairon", "Aggron" },
    ["Oddishruby"] = { "Oddish", "Gloom", "Vileplume" },
    ["Oddishsapphire"] = { "Oddish", "Gloom", "Bellossom" },
    ["Spoink"] = { "Spoink", "Grumpig" },
    ["Shuppet"] = { "Shuppet", "Banette" },
    ["Chimecho"] = { "Chimecho" },
    ["Natu"] = { "Natu", "Xatu" },
    ["Sandshrew"] = { "Sandshrew", "Sandslash" },
    ["Spinda"] = { "Spinda" },
    ["Trapinch"] = { "Trapinch", "Vibrava", "Flygon" },
    ["Phanpy"] = { "Phanpy", "Donphan" },
    ["Snorunt"] = { "Snorunt", "Glalie" },
    ["Spheal"] = { "Spheal", "Sealeo", "Walrein" },
    ["Corsola"] = { "Corsola" },
    ["Horsea"] = { "Horsea", "Seadra", "Kingdra" },
    ["Bagon"] = { "Bagon", "Shelgon", "Salamence" },
    ["Lotad"] = { "Lotad", "Lombre", "Ludicolo" },
    ["Surskit"] = { "Surskit", "Masquerain" },
    ["Azurill"] = { "Azurill", "Marill", "Azumarill" },
    ["Gulpin"] = { "Gulpin", "Swalot" },
    ["Igglybuff"] = { "Igglybuff", "Jigglypuff", "Wigglytuff" },
    ["Chinchou"] = { "Chinchou", "Lanturn" },
    ["Seedot"] = { "Seedot", "Nuzleaf", "Shiftry" },
    ["Shroomish"] = { "Shroomish", "Breloom" },
    ["Skitty"] = { "Skitty", "Delcatty" },
    ["Plusle"] = { "Plusle" },
    ["Minun"] = { "Minun" },
    ["Wynaut"] = { "Wynaut", "Wobbuffet" },
    ["Zigzagoon"] = { "Zigzagoon", "Linoone" },
    ["Nuzleaf"] = { "Nuzleaf", "Shiftry" },
    ["Treecko"] = { "Treecko", "Grovyle", "Sceptile" },
    ["Numel"] = { "Numel", "Camerupt" },
    ["Slugma"] = { "Slugma", "Magcargo" },
    ["Torkoal"] = { "Torkoal" },
    ["Koffing"] = { "Koffing", "Weezing" },
    ["Skarmory"] = { "Skarmory" },
    ["Vulpix"] = { "Vulpix", "Ninetales" },
    ["Torchic"] = { "Torchic", "Combusken", "Blaziken" },
    ["Illumise"] = { "Illumise" },
    ["Zangoose"] = { "Zangoose" },
    ["Wailmer"] = { "Wailmer", "Wailord" },
    ["Lileep"] = { "Lileep", "Cradily" },
    ["Staryu"] = { "Staryu", "Starmie" },
    ["Doduo"] = { "Doduo", "Dodrio" },
    ["Psyduck"] = { "Psyduck", "Golduck" },
    ["Wobbuffet"] = { "Wobbuffet" },
    ["Girafarig"] = { "Girafarig" },
    ["Pinsir"] = { "Pinsir" },
    ["Heracross"] = { "Heracross" },
    ["Rhyhorn"] = { "Rhyhorn", "Rhydon" },
    ["Pikachu"] = { "Pikachu", "Raichu" },
    ["Pichu"] = { "Pichu", "Pikachu", "Raichu" },
    ["Mawile"] = { "Mawile" },
    ["Machop"] = { "Machop", "Machoke", "Machamp" },
    ["Solrock"] = { "Solrock" },
    ["Beldum"] = { "Beldum", "Metang", "Metagross" },
    ["Regirock"] = { "Regirock" },
    ["Regice"] = { "Regice" },
    ["Jirachi"] = { "Jirachi" },
    ["Registeel"] = { "Registeel" },
    ["Silcoon"] = { "Silcoon", "Beautifly" },
    ["Cascoon"] = { "Cascoon", "Dustox" },
    ["Slakoth"] = { "Slakoth", "Vigoroth", "Slaking" },
    ["Roselia"] = { "Roselia" },
    ["Kecleon"] = { "Kecleon" },
    ["Duskull"] = { "Duskull", "Dusclops" },
    ["Nincada"] = { "Nincada", "Ninjask", "Shedinja" },
    ["Tropius"] = { "Tropius" },
    ["Lombre"] = { "Lombre", "Ludicolo" },
    ["Goldeen"] = { "Goldeen", "Seaking" },
    ["Marill"] = { "Marill", "Azumarill" },
    ["Barboach"] = { "Barboach", "Whiscash" },
    ["Corphish"] = { "Corphish", "Crawdaunt" },
    ["Feebas"] = { "Feebas", "Milotic" },
    ["Mudkip"] = { "Mudkip", "Marshtomp", "Swampert" },
    ["Poochyena"] = { "Poochyena", "Mightyena" },
    ["Taillow"] = { "Taillow", "Swellow" },
    ["Electrike"] = { "Electrike", "Manectric" },
    ["Magnemite"] = { "Magnemite", "Magneton" },
    ["Voltorb"] = { "Voltorb", "Electrode" },
    ["Jigglypuff"] = { "Jigglypuff", "Wigglytuff" },
    ["Castform"] = { "Castform" },
    ["Volbeat"] = { "Volbeat" },
    ["Seviper"] = { "Seviper" },
    ["Wingull"] = { "Wingull", "Pelipper" },
    ["Magikarp"] = { "Magikarp", "Gyarados" },
    ["Tentacool"] = { "Tentacool", "Tentacruel" },
    ["Carvanha"] = { "Carvanha", "Sharpedo" },
    ["Anorith"] = { "Anorith", "Armaldo" },
    ["Luvdisc"] = { "Luvdisc" },
    ["Clamperl"] = { "Clamperl", "Huntail", "Gorebyss" },
    ["Relicanth"] = { "Relicanth" },
    ["Geodude"] = { "Geodude", "Graveler", "Golem" },
    ["Meditite"] = { "Meditite", "Medicham" },
    ["Vibrava"] = { "Vibrava", "Flygon" },
    ["Cacnea"] = { "Cacnea", "Cacturne" },
    ["Baltoy"] = { "Baltoy", "Claydol" },
    ["Absol"] = { "Absol" },
    ["Swablu"] = { "Swablu", "Altaria" },
    ["Loudred"] = { "Loudred", "Exploud" },
    ["Makuhita"] = { "Makuhita", "Hariyama" },
    ["Nosepass"] = { "Nosepass" },
    ["Grimer"] = { "Grimer", "Muk" },
    ["Lunatone"] = { "Lunatone" },
    ["Shelgon"] = { "Shelgon", "Salamence" },
    ["Abra"] = { "Abra", "Kadabra", "Alakazam" },
    ["Sableye"] = { "Sableye" },
    ["Aerodactyl"] = { "Aerodactyl" },
    ["Chikorita"] = { "Chikorita" },
    ["Totodile"] = { "Totodile" },
    ["Cyndaquil"] = { "Cyndaquil" },
    ["Latias"] = { "Latias" },
    ["Latios"] = { "Latios" },
    ["Rayquaza"] = { "Rayquaza" },
    ["Kyogre"] = { "Kyogre" },
    ["Groudon"] = { "Groudon" }
}


AREA_NAMES = {
    [1] = "forestR",
    [2] = "volcanoR",
    [3] = "plainsR",
    [4] = "oceanR",
    [5] = "safariR",
    [6] = "caveR",
    [7] = "ruinsR",
    [8] = "forestS",
    [9] = "lakeS",
    [10] = "plainsS",
    [11] = "wildernessS",
    [12] = "oceanS",
    [13] = "caveS",
    [14] = "ruinsS",
    [15] = "egg1",
    [16] = "egg2",
    [17] = "egg3",
    [18] = "egg4",
    [19] = "eggruby",
    [20] = "eggsapphire",
    [21] = "chiko",
    [22] = "toto",
    [23] = "guest",
    [24] = "ratecard",
    [25] = "get",
    [26] = "ruby",
    [27] = "sapphire",
    [28] = "ruinscard",
    [29] = "evo",
    [30] = "aero",
    [31] = "cynda",
    [32] = "startcoins",
    [33] = "startball",
    [34] = "perpichu"

}


AREA_NAMES_RUBY = {
    [1] = "forestR",
    [2] = "volcanoR",
    [3] = "plainsR",
    [4] = "oceanR",
    [5] = "safariR",
    [6] = "caveR",
    [7] = "ruinsR"
}


AREA_NAMES_SAPPHIRE = {

    [1] = "forestS",
    [2] = "lakeS",
    [3] = "plainsS",
    [4] = "wildernessS",
    [5] = "oceanS",
    [6] = "caveS",
    [7] = "ruinsS"
}


POKEMON_RUBY_AREA = {
    ["caveR"] = {
        { "Loudred",  2, false },
        { "Nosepass", 2, true },
        { "Mawile",   2, false },
        { "Machop",   2, false },
        { "Grimer",   2, false },
        { "Solrock",  2, false },
        { "Shelgon",  2, false },
        { "Abra",     3, false },
    },
    ["forestR"] = {
        { "Zigzagoon", 2, false },
        { "Silcoon",   2, false },
        { "Cascoon",   2, false },
        { "Nuzleaf",   2, false },
        { "Kecleon",   2, true },
        { "Duskull",   2, false },
        { "Treecko",   3, false },
        { "Nincada",   3, false },
    },
    ["oceanR"] = {
        { "Wingull",   2, false },
        { "Tentacool", 2, false },
        { "Carvanha",  2, false },
        { "Wailmer",   2, false },
        { "Lileep",    2, true },
        { "Luvdisc",   2, false },
        { "Staryu",    3, false },
        { "Relicanth", 3, false },
    },
    ["plainsR"] = {
        { "Poochyena", 2, false },
        { "Taillow",   2, false },
        { "Electrike", 2, false },
        { "Magnemite", 2, false },
        { "Voltorb",   2, false },
        { "Illumise",  2, false },
        { "Castform",  2, true },
        { "Zangoose",  3, false },
    },
    ["ruinsR"] = {
        { "Beldum",    2, false },
        { "Regirock",  2, false },
        { "Regice",    2, false },
        { "Jirachi",   2, false },
        { "Registeel", 3, false },
    },
    ["safariR"] = {
        { "Doduo",     2, false },
        { "Psyduck",   2, false },
        { "Wobbuffet", 2, true },
        { "Girafarig", 2, false },
        { "Pinsir",    2, false },
        { "Heracross", 2, false },
        { "Rhyhorn",   2, false },
        { "Pikachu",   3, false },
    },
    ["volcanoR"] = {
        { "Numel",    2, false },
        { "Slugma",   2, false },
        { "Torkoal",  2, false },
        { "Koffing",  2, false },
        { "Skarmory", 2, true },
        { "Vulpix",   2, false },
        { "Torchic",  3, false },
    },
}



POKEMON_SAPPHIRE_AREA = {

    ["caveS"] = {
        { "Loudred",  2, false },
        { "Makuhita", 2, false },
        { "Nosepass", 2, true },
        { "Grimer",   2, false },
        { "Lunatone", 2, false },
        { "Shelgon",  2, false },
        { "Abra",     3, false },
        { "Sableye",  3, false },
    },
    ["forestS"] = {
        { "Silcoon", 2, false },
        { "Cascoon", 2, false },
        { "Slakoth", 2, false },
        { "Roselia", 2, false },
        { "Kecleon", 2, true },
        { "Duskull", 2, false },
        { "Nincada", 3, false },
        { "Tropius", 3, false },
    },
    ["lakeS"] = {
        { "Lombre",   2, false },
        { "Goldeen",  2, false },
        { "Marill",   2, false },
        { "Barboach", 2, false },
        { "Corphish", 2, false },
        { "Feebas",   2, true },
        { "Mudkip",   3, false },
    },
    ["oceanS"] = {
        { "Wingull",   2, false },
        { "Magikarp",  2, false },
        { "Tentacool", 2, false },
        { "Carvanha",  2, false },
        { "Anorith",   2, true },
        { "Luvdisc",   2, false },
        { "Clamperl",  3, false },
        { "Relicanth", 3, false },
    },
    ["plainsS"] = {
        { "Poochyena",  2, false },
        { "Taillow",    2, false },
        { "Electrike",  2, false },
        { "Magnemite",  2, false },
        { "Voltorb",    2, false },
        { "Jigglypuff", 2, false },
        { "Castform",   2, true },
        { "Volbeat",    3, false },
        { "Seviper",    3, false },
    },
    ["ruinsS"] = {
        { "Beldum",    2, false },
        { "Regirock",  2, false },
        { "Regice",    2, false },
        { "Jirachi",   2, false },
        { "Registeel", 3, false },
    },
    ["wildernessS"] = {
        { "Geodude",  2, false },
        { "Meditite", 2, false },
        { "Vibrava",  2, false },
        { "Cacnea",   2, false },
        { "Baltoy",   2, false },
        { "Absol",    2, true },
        { "Swablu",   3, false },
    }
}


POKEMON_RUBY_EGG = {
    ["egg1"] = {
        { "Wurmple" },
        { "Wurmple " },
        { "Ralts" },
        { "Whismur" },
        { "Zubat" },
        { "Aron" }
    },

    ["egg2"] = {
        { "Oddish" },
        { "Spoink" },
        { "Shuppet" },
        { "Chimecho" },
        { "Natu" }
    },

    ["egg3"] = {
        { "Sandshrew" },
        { "Spinda" },
        { "Trapinch" },
        { "Phanpy" }
    },

    ["egg4"] = {
        { "Snorunt" },
        { "Spheal" },
        { "Corsola" },
        { "Horsea" },
        { "Bagon" }
    },

    ["eggruby"] = {
        { "Seedot" },
        { "Shroomish" },
        { "Skitty" },
        { "Plusle" },
        { "Minun" },
        { "Wynaut" }
    }

}

POKEMON_SAPPHIRE_EGG = {
    ["egg1"] = {
        { "Wurmple" },
        { "Wurmple " },
        { "Ralts" },
        { "Whismur" },
        { "Zubat" },
        { "Aron" }
    },

    ["egg2"] = {
        { "Oddish" },
        { "Spoink" },
        { "Shuppet" },
        { "Chimecho" },
        { "Natu" }
    },

    ["egg3"] = {
        { "Sandshrew" },
        { "Spinda" },
        { "Trapinch" },
        { "Phanpy" }
    },

    ["egg4"] = {
        { "Snorunt" },
        { "Spheal" },
        { "Corsola" },
        { "Horsea" },
        { "Bagon" }
    },

    ["eggsapphire"] = {
        { "Lotad" },
        { "Surskit" },
        { "Azurill" },
        { "Gulpin" },
        { "Igglybuff" },
        { "Chinchou" }
    }

}

POKEMON_RUBY = {
    ["Loudred"] = { 2, false },
    ["Nosepass"] = { 2, true },
    ["Mawile"] = { 2, false },
    ["Machop"] = { 2, false },
    ["Grimer"] = { 2, false },
    ["Solrock"] = { 2, false },
    ["Shelgon"] = { 2, false },
    ["Abra"] = { 3, false },
    ["Zigzagoon"] = { 2, false },
    ["Silcoon"] = { 2, false },
    ["Cascoon"] = { 2, false },
    ["Nuzleaf"] = { 2, false },
    ["Kecleon"] = { 2, true },
    ["Duskull"] = { 2, false },
    ["Treecko"] = { 3, false },
    ["Nincada"] = { 3, false },
    ["Wingull"] = { 2, false },
    ["Tentacool"] = { 2, false },
    ["Carvanha"] = { 2, false },
    ["Wailmer"] = { 2, false },
    ["Lileep"] = { 2, true },
    ["Luvdisc"] = { 2, false },
    ["Staryu"] = { 3, false },
    ["Relicanth"] = { 3, false },
    ["Poochyena"] = { 2, false },
    ["Taillow"] = { 2, false },
    ["Electrike"] = { 2, false },
    ["Magnemite"] = { 2, false },
    ["Voltorb"] = { 2, false },
    ["Illumise"] = { 2, false },
    ["Castform"] = { 2, true },
    ["Zangoose"] = { 3, false },
    ["Beldum"] = { 2, false },
    ["Regirock"] = { 2, false },
    ["Regice"] = { 2, false },
    ["Jirachi"] = { 2, false },
    ["Registeel"] = { 3, false },
    ["Doduo"] = { 2, false },
    ["Psyduck"] = { 2, false },
    ["Wobbuffet"] = { 2, true },
    ["Girafarig"] = { 2, false },
    ["Pinsir"] = { 2, false },
    ["Heracross"] = { 2, false },
    ["Rhyhorn"] = { 2, false },
    ["Pikachu"] = { 3, false },
    ["Numel"] = { 2, false },
    ["Slugma"] = { 2, false },
    ["Torkoal"] = { 2, false },
    ["Koffing"] = { 2, false },
    ["Skarmory"] = { 2, true },
    ["Vulpix"] = { 2, false },
    ["Torchic"] = { 3, false },


}


POKEMON_SAPPHIRE = {
    ["Loudred"] = { 2, false },
    ["Makuhita"] = { 2, false },
    ["Nosepass"] = { 2, true },
    ["Grimer"] = { 2, false },
    ["Lunatone"] = { 2, false },
    ["Shelgon"] = { 2, false },
    ["Abra"] = { 3, false },
    ["Sableye"] = { 3, false },
    ["Silcoon"] = { 2, false },
    ["Cascoon"] = { 2, false },
    ["Slakoth"] = { 2, false },
    ["Roselia"] = { 2, false },
    ["Kecleon"] = { 2, true },
    ["Duskull"] = { 2, false },
    ["Nincada"] = { 3, false },
    ["Tropius"] = { 3, false },
    ["Lombre"] = { 2, false },
    ["Goldeen"] = { 2, false },
    ["Marill"] = { 2, false },
    ["Barboach"] = { 2, false },
    ["Corphish"] = { 2, false },
    ["Feebas"] = { 2, true },
    ["Mudkip"] = { 3, false },
    ["Wingull"] = { 2, false },
    ["Magikarp"] = { 2, false },
    ["Tentacool"] = { 2, false },
    ["Carvanha"] = { 2, false },
    ["Anorith"] = { 2, true },
    ["Luvdisc"] = { 2, false },
    ["Clamperl"] = { 3, false },
    ["Relicanth"] = { 3, false },
    ["Poochyena"] = { 2, false },
    ["Taillow"] = { 2, false },
    ["Electrike"] = { 2, false },
    ["Magnemite"] = { 2, false },
    ["Voltorb"] = { 2, false },
    ["Jigglypuff"] = { 2, false },
    ["Castform"] = { 2, true },
    ["Volbeat"] = { 3, false },
    ["Seviper"] = { 3, false },
    ["Beldum"] = { 2, false },
    ["Regirock"] = { 2, false },
    ["Regice"] = { 2, false },
    ["Jirachi"] = { 2, false },
    ["Registeel"] = { 3, false },
    ["Geodude"] = { 2, false },
    ["Meditite"] = { 2, false },
    ["Vibrava"] = { 2, false },
    ["Cacnea"] = { 2, false },
    ["Baltoy"] = { 2, false },
    ["Absol"] = { 2, true },
    ["Swablu"] = { 3, false }

}

POKEMON_EVO = {
    [1] = "Grovyle",
    [2] = "Sceptile",
    [3] = "Combusken",
    [4] = "Blaziken",
    [5] = "Marshtomp",
    [6] = "Swampert",
    [7] = "Mightyena",
    [8] = "Linoone",
    [9] = "Silcoon",
    [10] = "Beautifly",
    [11] = "Cascoon",
    [12] = "Dustox",
    [13] = "Lombre",
    [14] = "Ludicolo",
    [15] = "Nuzleaf",
    [16] = "Shiftry",
    [17] = "Swellow",
    [18] = "Pelipper",
    [19] = "Kirlia",
    [20] = "Gardevoir",
    [21] = "Masquerain",
    [22] = "Breloom",
    [23] = "Vigoroth",
    [24] = "Slaking",
    [25] = "Kadabra",
    [26] = "Alakazam",
    [27] = "Ninjask",
    [28] = "Shedinja",
    [29] = "Loudred",
    [30] = "Exploud",
    [31] = "Hariyama",
    [32] = "Seaking",
    [33] = "Gyarados",
    [34] = "Marill",
    [35] = "Azumarill",
    [36] = "Graveler",
    [37] = "Golem",
    [38] = "Delcatty",
    [39] = "Golbat",
    [40] = "Crobat",
    [41] = "Tentacruel",
    [42] = "Lairon",
    [43] = "Aggron",
    [44] = "Machoke",
    [45] = "Machamp",
    [46] = "Medicham",
    [47] = "Manectric",
    [48] = "Magneton",
    [49] = "Electrode",
    [50] = "Gloom",
    [51] = "Vileplume",
    [52] = "Bellossom",
    [53] = "Dodrio",
    [54] = "Swalot",
    [55] = "Sharpedo",
    [56] = "Wailord",
    [57] = "Camerupt",
    [58] = "Magcargo",
    [59] = "Muk",
    [60] = "Weezing",
    [61] = "Grumpig",
    [62] = "Sandslash",
    [63] = "Vibrava",
    [64] = "Flygon",
    [65] = "Cacturne",
    [66] = "Altaria",
    [67] = "Whiscash",
    [68] = "Crawdaunt",
    [69] = "Claydol",
    [70] = "Cradily",
    [71] = "Armaldo",
    [72] = "Jigglypuff",
    [73] = "Wigglytuff",
    [74] = "Milotic",
    [75] = "Starmie",
    [76] = "Banette",
    [77] = "Dusclops",
    [78] = "Ninetales",
    [79] = "Pikachu",
    [80] = "Raichu",
    [81] = "Golduck",
    [82] = "Wobbuffet",
    [83] = "Xatu",
    [84] = "Donphan",
    [85] = "Rhydon",
    [86] = "Glalie",
    [87] = "Sealeo",
    [88] = "Walrein",
    [89] = "Huntail",
    [90] = "Gorebyss",
    [91] = "Lanturn",
    [92] = "Seadra",
    [93] = "Kingdra",
    [94] = "Shelgon",
    [95] = "Salamence",
    [96] = "Metang",
    [97] = "Metagross"

}
