HIGHLIGHT_STATUS_MAPPING = {
    [0] = 2,   --Unspecified
    [10] = 1,  -- NoPriority
    [20] = -1, -- Avoid
    [30] = 3,  -- Priority
    [40] = 0   -- None
}

Pokemon = {
    [1] = "Treecko",
    [2] = "Grovyle",
    [3] = "Sceptile",
    [4] = "Torchic",
    [5] = "Combusken",
    [6] = "Blaziken",
    [7] = "Mudkip",
    [8] = "Marshtomp",
    [9] = "Swampert",
    [10] = "Poochyena",
    [11] = "Mightyena",
    [12] = "Zigzagoon",
    [13] = "Linoone",
    [14] = "Wurmple",
    [15] = "Silcoon",
    [16] = "Beautifly",
    [17] = "Cascoon",
    [18] = "Dustox",
    [19] = "Lotad",
    [20] = "Lombre",
    [21] = "Ludicolo",
    [22] = "Seedot",
    [23] = "Nuzleaf",
    [24] = "Shiftry",
    [25] = "Taillow",
    [26] = "Swellow",
    [27] = "Wingull",
    [28] = "Pelipper",
    [29] = "Ralts",
    [30] = "Kirlia",
    [31] = "Gardevoir",
    [32] = "Surskit",
    [33] = "Masquerain",
    [34] = "Shroomish",
    [35] = "Breloom",
    [36] = "Slakoth",
    [37] = "Vigoroth",
    [38] = "Slaking",
    [39] = "Abra",
    [40] = "Kadabra",
    [41] = "Alakazam",
    [42] = "Nincada",
    [43] = "Ninjask",
    [44] = "Shedinja",
    [45] = "Whismur",
    [46] = "Loudred",
    [47] = "Exploud",
    [48] = "Makuhita",
    [49] = "Hariyama",
    [50] = "Goldeen",
    [51] = "Seaking",
    [52] = "Magikarp",
    [53] = "Gyarados",
    [54] = "Azurill",
    [55] = "Marill",
    [56] = "Azumarill",
    [57] = "Geodude",
    [58] = "Graveler",
    [59] = "Golem",
    [60] = "Nosepass",
    [61] = "Skitty",
    [62] = "Delcatty",
    [63] = "Zubat",
    [64] = "Golbat",
    [65] = "Crobat",
    [66] = "Tentacool",
    [67] = "Tentacruel",
    [68] = "Sableye",
    [69] = "Mawile",
    [70] = "Aron",
    [71] = "Lairon",
    [72] = "Aggron",
    [73] = "Machop",
    [74] = "Machoke",
    [75] = "Machamp",
    [76] = "Meditite",
    [77] = "Medicham",
    [78] = "Electrike",
    [79] = "Manectric",
    [80] = "Plusle",
    [81] = "Minun",
    [82] = "Magnemite",
    [83] = "Magneton",
    [84] = "Voltorb",
    [85] = "Electrode",
    [86] = "Volbeat",
    [87] = "Illumise",
    [88] = "Oddish",
    [89] = "Gloom",
    [90] = "Vileplume",
    [91] = "Bellossom",
    [92] = "Doduo",
    [93] = "Dodrio",
    [94] = "Roselia",
    [95] = "Gulpin",
    [96] = "Swalot",
    [97] = "Carvanha",
    [98] = "Sharpedo",
    [99] = "Wailmer",
    [100] = "Wailord",
    [101] = "Numel",
    [102] = "Camerupt",
    [103] = "Slugma",
    [104] = "Magcargo",
    [105] = "Torkoal",
    [106] = "Grimer",
    [107] = "Muk",
    [108] = "Koffing",
    [109] = "Weezing",
    [110] = "Spoink",
    [111] = "Grumpig",
    [112] = "Sandshrew",
    [113] = "Sandslash",
    [114] = "Spinda",
    [115] = "Skarmory",
    [116] = "Trapinch",
    [117] = "Vibrava",
    [118] = "Flygon",
    [119] = "Cacnea",
    [120] = "Cacturne",
    [121] = "Swablu",
    [122] = "Altaria",
    [123] = "Zangoose",
    [124] = "Seviper",
    [125] = "Lunatone",
    [126] = "Solrock",
    [127] = "Barboach",
    [128] = "Whiscash",
    [129] = "Corphish",
    [130] = "Crawdaunt",
    [131] = "Baltoy",
    [132] = "Claydol",
    [133] = "Lileep",
    [134] = "Cradily",
    [135] = "Anorith",
    [136] = "Armaldo",
    [137] = "Igglybuff",
    [138] = "Jigglypuff",
    [139] = "Wigglytuff",
    [140] = "Feebas",
    [141] = "Milotic",
    [142] = "Castform",
    [143] = "Staryu",
    [144] = "Starmie",
    [145] = "Kecleon",
    [146] = "Shuppet",
    [147] = "Banette",
    [148] = "Duskull",
    [149] = "Dusclops",
    [150] = "Tropius",
    [151] = "Chimecho",
    [152] = "Absol",
    [153] = "Vulpix",
    [154] = "Ninetales",
    [155] = "Pichu",
    [156] = "Pikachu",
    [157] = "Raichu",
    [158] = "Psyduck",
    [159] = "Golduck",
    [160] = "Wynaut",
    [161] = "Wobbuffet",
    [162] = "Natu",
    [163] = "Xatu",
    [164] = "Girafarig",
    [165] = "Phanpy",
    [166] = "Donphan",
    [167] = "Pinsir",
    [168] = "Heracross",
    [169] = "Rhyhorn",
    [170] = "Rhydon",
    [171] = "Snorunt",
    [172] = "Glalie",
    [173] = "Spheal",
    [174] = "Sealeo",
    [175] = "Walrein",
    [176] = "Clamperl",
    [177] = "Huntail",
    [178] = "Gorebyss",
    [179] = "Relicanth",
    [180] = "Corsola",
    [181] = "Chinchou",
    [182] = "Lanturn",
    [183] = "Luvdisc",
    [184] = "Horsea",
    [185] = "Seadra",
    [186] = "Kingdra",
    [187] = "Bagon",
    [188] = "Shelgon",
    [189] = "Salamence",
    [190] = "Beldum",
    [191] = "Metang",
    [192] = "Metagross",
    [193] = "Regirock",
    [194] = "Regice",
    [195] = "Registeel",
    [196] = "Latias",
    [197] = "Latios",
    [198] = "Kyogre",
    [199] = "Groudon",
    [200] = "Rayquaza",
    [201] = "Jirachi",
    [202] = "Chikorita",
    [203] = "Cyndaquil",
    [204] = "Totodile",
    [205] = "Aerodactyl"


}


PokemonZero = {
    [0] = "Treecko",
    [1] = "Grovyle",
    [2] = "Sceptile",
    [3] = "Torchic",
    [4] = "Combusken",
    [5] = "Blaziken",
    [6] = "Mudkip",
    [7] = "Marshtomp",
    [8] = "Swampert",
    [9] = "Poochyena",
    [10] = "Mightyena",
    [11] = "Zigzagoon",
    [12] = "Linoone",
    [13] = "Wurmple",
    [14] = "Silcoon",
    [15] = "Beautifly",
    [16] = "Cascoon",
    [17] = "Dustox",
    [18] = "Lotad",
    [19] = "Lombre",
    [20] = "Ludicolo",
    [21] = "Seedot",
    [22] = "Nuzleaf",
    [23] = "Shiftry",
    [24] = "Taillow",
    [25] = "Swellow",
    [26] = "Wingull",
    [27] = "Pelipper",
    [28] = "Ralts",
    [29] = "Kirlia",
    [30] = "Gardevoir",
    [31] = "Surskit",
    [32] = "Masquerain",
    [33] = "Shroomish",
    [34] = "Breloom",
    [35] = "Slakoth",
    [36] = "Vigoroth",
    [37] = "Slaking",
    [38] = "Abra",
    [39] = "Kadabra",
    [40] = "Alakazam",
    [41] = "Nincada",
    [42] = "Ninjask",
    [43] = "Shedinja",
    [44] = "Whismur",
    [45] = "Loudred",
    [46] = "Exploud",
    [47] = "Makuhita",
    [48] = "Hariyama",
    [49] = "Goldeen",
    [50] = "Seaking",
    [51] = "Magikarp",
    [52] = "Gyarados",
    [53] = "Azurill",
    [54] = "Marill",
    [55] = "Azumarill",
    [56] = "Geodude",
    [57] = "Graveler",
    [58] = "Golem",
    [59] = "Nosepass",
    [60] = "Skitty",
    [61] = "Delcatty",
    [62] = "Zubat",
    [63] = "Golbat",
    [64] = "Crobat",
    [65] = "Tentacool",
    [66] = "Tentacruel",
    [67] = "Sableye",
    [68] = "Mawile",
    [69] = "Aron",
    [70] = "Lairon",
    [71] = "Aggron",
    [72] = "Machop",
    [73] = "Machoke",
    [74] = "Machamp",
    [75] = "Meditite",
    [76] = "Medicham",
    [77] = "Electrike",
    [78] = "Manectric",
    [79] = "Plusle",
    [80] = "Minun",
    [81] = "Magnemite",
    [82] = "Magneton",
    [83] = "Voltorb",
    [84] = "Electrode",
    [85] = "Volbeat",
    [86] = "Illumise",
    [87] = "Oddish",
    [88] = "Gloom",
    [89] = "Vileplume",
    [90] = "Bellossom",
    [91] = "Doduo",
    [92] = "Dodrio",
    [93] = "Roselia",
    [94] = "Gulpin",
    [95] = "Swalot",
    [96] = "Carvanha",
    [97] = "Sharpedo",
    [98] = "Wailmer",
    [99] = "Wailord",
    [100] = "Numel",
    [101] = "Camerupt",
    [102] = "Slugma",
    [103] = "Magcargo",
    [104] = "Torkoal",
    [105] = "Grimer",
    [106] = "Muk",
    [107] = "Koffing",
    [108] = "Weezing",
    [109] = "Spoink",
    [110] = "Grumpig",
    [111] = "Sandshrew",
    [112] = "Sandslash",
    [113] = "Spinda",
    [114] = "Skarmory",
    [115] = "Trapinch",
    [116] = "Vibrava",
    [117] = "Flygon",
    [118] = "Cacnea",
    [119] = "Cacturne",
    [120] = "Swablu",
    [121] = "Altaria",
    [122] = "Zangoose",
    [123] = "Seviper",
    [124] = "Lunatone",
    [125] = "Solrock",
    [126] = "Barboach",
    [127] = "Whiscash",
    [128] = "Corphish",
    [129] = "Crawdaunt",
    [130] = "Baltoy",
    [131] = "Claydol",
    [132] = "Lileep",
    [133] = "Cradily",
    [134] = "Anorith",
    [135] = "Armaldo",
    [136] = "Igglybuff",
    [137] = "Jigglypuff",
    [138] = "Wigglytuff",
    [139] = "Feebas",
    [140] = "Milotic",
    [141] = "Castform",
    [142] = "Staryu",
    [143] = "Starmie",
    [144] = "Kecleon",
    [145] = "Shuppet",
    [146] = "Banette",
    [147] = "Duskull",
    [148] = "Dusclops",
    [149] = "Tropius",
    [150] = "Chimecho",
    [151] = "Absol",
    [152] = "Vulpix",
    [153] = "Ninetales",
    [154] = "Pichu",
    [155] = "Pikachu",
    [156] = "Raichu",
    [157] = "Psyduck",
    [158] = "Golduck",
    [159] = "Wynaut",
    [160] = "Wobbuffet",
    [161] = "Natu",
    [162] = "Xatu",
    [163] = "Girafarig",
    [164] = "Phanpy",
    [165] = "Donphan",
    [166] = "Pinsir",
    [167] = "Heracross",
    [168] = "Rhyhorn",
    [169] = "Rhydon",
    [170] = "Snorunt",
    [171] = "Glalie",
    [172] = "Spheal",
    [173] = "Sealeo",
    [174] = "Walrein",
    [175] = "Clamperl",
    [176] = "Huntail",
    [177] = "Gorebyss",
    [178] = "Relicanth",
    [179] = "Corsola",
    [180] = "Chinchou",
    [181] = "Lanturn",
    [182] = "Luvdisc",
    [183] = "Horsea",
    [184] = "Seadra",
    [185] = "Kingdra",
    [186] = "Bagon",
    [187] = "Shelgon",
    [188] = "Salamence",
    [189] = "Beldum",
    [190] = "Metang",
    [191] = "Metagross",
    [192] = "Regirock",
    [193] = "Regice",
    [194] = "Registeel",
    [195] = "Latias",
    [196] = "Latios",
    [197] = "Kyogre",
    [198] = "Groudon",
    [199] = "Rayquaza",
    [200] = "Jirachi",
    [201] = "Chikorita",
    [202] = "Cyndaquil",
    [203] = "Totodile",
    [204] = "Aerodactyl"

}

POKEMON_INVERSE = {

    ["Treecko"] = 1,
    ["Grovyle"] = 2,
    ["Sceptile"] = 3,
    ["Torchic"] = 4,
    ["Combusken"] = 5,
    ["Blaziken"] = 6,
    ["Mudkip"] = 7,
    ["Marshtomp"] = 8,
    ["Swampert"] = 9,
    ["Poochyena"] = 10,
    ["Mightyena"] = 11,
    ["Zigzagoon"] = 12,
    ["Linoone"] = 13,
    ["Wurmple"] = 14,
    ["Silcoon"] = 15,
    ["Beautifly"] = 16,
    ["Cascoon"] = 17,
    ["Dustox"] = 18,
    ["Lotad"] = 19,
    ["Lombre"] = 20,
    ["Ludicolo"] = 21,
    ["Seedot"] = 22,
    ["Nuzleaf"] = 23,
    ["Shiftry"] = 24,
    ["Taillow"] = 25,
    ["Swellow"] = 26,
    ["Wingull"] = 27,
    ["Pelipper"] = 28,
    ["Ralts"] = 29,
    ["Kirlia"] = 30,
    ["Gardevoir"] = 31,
    ["Surskit"] = 32,
    ["Masquerain"] = 33,
    ["Shroomish"] = 34,
    ["Breloom"] = 35,
    ["Slakoth"] = 36,
    ["Vigoroth"] = 37,
    ["Slaking"] = 38,
    ["Abra"] = 39,
    ["Kadabra"] = 40,
    ["Alakazam"] = 41,
    ["Nincada"] = 42,
    ["Ninjask"] = 43,
    ["Shedinja"] = 44,
    ["Whismur"] = 45,
    ["Loudred"] = 46,
    ["Exploud"] = 47,
    ["Makuhita"] = 48,
    ["Hariyama"] = 49,
    ["Goldeen"] = 50,
    ["Seaking"] = 51,
    ["Magikarp"] = 52,
    ["Gyarados"] = 53,
    ["Azurill"] = 54,
    ["Marill"] = 55,
    ["Azumarill"] = 56,
    ["Geodude"] = 57,
    ["Graveler"] = 58,
    ["Golem"] = 59,
    ["Nosepass"] = 60,
    ["Skitty"] = 61,
    ["Delcatty"] = 62,
    ["Zubat"] = 63,
    ["Golbat"] = 64,
    ["Crobat"] = 65,
    ["Tentacool"] = 66,
    ["Tentacruel"] = 67,
    ["Sableye"] = 68,
    ["Mawile"] = 69,
    ["Aron"] = 70,
    ["Lairon"] = 71,
    ["Aggron"] = 72,
    ["Machop"] = 73,
    ["Machoke"] = 74,
    ["Machamp"] = 75,
    ["Meditite"] = 76,
    ["Medicham"] = 77,
    ["Electrike"] = 78,
    ["Manectric"] = 79,
    ["Plusle"] = 80,
    ["Minun"] = 81,
    ["Magnemite"] = 82,
    ["Magneton"] = 83,
    ["Voltorb"] = 84,
    ["Electrode"] = 85,
    ["Volbeat"] = 86,
    ["Illumise"] = 87,
    ["Oddish"] = 88,
    ["Gloom"] = 89,
    ["Vileplume"] = 90,
    ["Bellossom"] = 91,
    ["Doduo"] = 92,
    ["Dodrio"] = 93,
    ["Roselia"] = 94,
    ["Gulpin"] = 95,
    ["Swalot"] = 96,
    ["Carvanha"] = 97,
    ["Sharpedo"] = 98,
    ["Wailmer"] = 99,
    ["Wailord"] = 100,
    ["Numel"] = 101,
    ["Camerupt"] = 102,
    ["Slugma"] = 103,
    ["Magcargo"] = 104,
    ["Torkoal"] = 105,
    ["Grimer"] = 106,
    ["Muk"] = 107,
    ["Koffing"] = 108,
    ["Weezing"] = 109,
    ["Spoink"] = 110,
    ["Grumpig"] = 111,
    ["Sandshrew"] = 112,
    ["Sandslash"] = 113,
    ["Spinda"] = 114,
    ["Skarmory"] = 115,
    ["Trapinch"] = 116,
    ["Vibrava"] = 117,
    ["Flygon"] = 118,
    ["Cacnea"] = 119,
    ["Cacturne"] = 120,
    ["Swablu"] = 121,
    ["Altaria"] = 122,
    ["Zangoose"] = 123,
    ["Seviper"] = 124,
    ["Lunatone"] = 125,
    ["Solrock"] = 126,
    ["Barboach"] = 127,
    ["Whiscash"] = 128,
    ["Corphish"] = 129,
    ["Crawdaunt"] = 130,
    ["Baltoy"] = 131,
    ["Claydol"] = 132,
    ["Lileep"] = 133,
    ["Cradily"] = 134,
    ["Anorith"] = 135,
    ["Armaldo"] = 136,
    ["Igglybuff"] = 137,
    ["Jigglypuff"] = 138,
    ["Wigglytuff"] = 139,
    ["Feebas"] = 140,
    ["Milotic"] = 141,
    ["Castform"] = 142,
    ["Staryu"] = 143,
    ["Starmie"] = 144,
    ["Kecleon"] = 145,
    ["Shuppet"] = 146,
    ["Banette"] = 147,
    ["Duskull"] = 148,
    ["Dusclops"] = 149,
    ["Tropius"] = 150,
    ["Chimecho"] = 151,
    ["Absol"] = 152,
    ["Vulpix"] = 153,
    ["Ninetales"] = 154,
    ["Pichu"] = 155,
    ["Pikachu"] = 156,
    ["Raichu"] = 157,
    ["Psyduck"] = 158,
    ["Golduck"] = 159,
    ["Wynaut"] = 160,
    ["Wobbuffet"] = 161,
    ["Natu"] = 162,
    ["Xatu"] = 163,
    ["Girafarig"] = 164,
    ["Phanpy"] = 165,
    ["Donphan"] = 166,
    ["Pinsir"] = 167,
    ["Heracross"] = 168,
    ["Rhyhorn"] = 169,
    ["Rhydon"] = 170,
    ["Snorunt"] = 171,
    ["Glalie"] = 172,
    ["Spheal"] = 173,
    ["Sealeo"] = 174,
    ["Walrein"] = 175,
    ["Clamperl"] = 176,
    ["Huntail"] = 177,
    ["Gorebyss"] = 178,
    ["Relicanth"] = 179,
    ["Corsola"] = 180,
    ["Chinchou"] = 181,
    ["Lanturn"] = 182,
    ["Luvdisc"] = 183,
    ["Horsea"] = 184,
    ["Seadra"] = 185,
    ["Kingdra"] = 186,
    ["Bagon"] = 187,
    ["Shelgon"] = 188,
    ["Salamence"] = 189,
    ["Beldum"] = 190,
    ["Metang"] = 191,
    ["Metagross"] = 192,
    ["Regirock"] = 193,
    ["Regice"] = 194,
    ["Registeel"] = 195,
    ["Latias"] = 196,
    ["Latios"] = 197,
    ["Kyogre"] = 198,
    ["Groudon"] = 199,
    ["Rayquaza"] = 200,
    ["Jirachi"] = 201,
    ["Chikorita"] = 202,
    ["Cyndaquil"] = 203,
    ["Totodile"] = 204,
    ["Aerodactyl"] = 205,

}

AREAS = {
    {
        { 22,  2 },
        { 11,  2 },
        { 14,  2 },
        { 16,  2 },
        { 147, 2 },
        { 144, 2 },
        { 0,   3 },
        { 41,  3 }
    },
    {
        { 102, 2 },
        { 152, 2 },
        { 104, 2 },
        { 100, 2 },
        { 107, 2 },
        { 114, 2 },
        { 3,   3 }
    },
    {
        { 86,  2 },
        { 77,  2 },
        { 9,   2 },
        { 81,  2 },
        { 83,  2 },
        { 24,  2 },
        { 141, 2 },
        { 122, 3 }
    },
    {
        { 98,  2 },
        { 26,  2 },
        { 65,  2 },
        { 96,  2 },
        { 182, 2 },
        { 132, 2 },
        { 142, 3 },
        { 178, 3 }
    },
    {
        { 157, 2 },
        { 167, 2 },
        { 163, 2 },
        { 166, 2 },
        { 168, 2 },
        { 91,  2 },
        { 160, 2 },
        { 155, 3 }
    },
    {
        { 125, 2 },
        { 68,  2 },
        { 72,  2 },
        { 105, 2 },
        { 187, 2 },
        { 45,  2 },
        { 59,  2 },
        { 38,  3 }
    },
    {
        { 189, 2 },
        { 192, 2 },
        { 193, 2 },
        { 194, 3 },
        { 200, 2 }
    },
    {
        { 35,  2 },
        { 93,  2 },
        { 14,  2 },
        { 16,  2 },
        { 147, 2 },
        { 144, 2 },
        { 149, 3 },
        { 41,  3 }
    },
    {
        { 49,  2 },
        { 54,  2 },
        { 19,  2 },
        { 126, 2 },
        { 128, 2 },
        { 139, 2 },
        { 6,   3 }
    },
    {
        { 137, 2 },
        { 77,  2 },
        { 9,   2 },
        { 81,  2 },
        { 83,  2 },
        { 24,  2 },
        { 141, 2 },
        { 85,  3 },
        { 123, 3 }
    },
    {
        { 130, 2 },
        { 75,  2 },
        { 116, 2 },
        { 118, 2 },
        { 56,  2 },
        { 151, 2 },
        { 120, 3 }
    },
    {
        { 51,  2 },
        { 26,  2 },
        { 65,  2 },
        { 96,  2 },
        { 182, 2 },
        { 134, 2 },
        { 175, 3 },
        { 178, 3 }
    },
    {
        { 124, 2 },
        { 67,  3 },
        { 47,  2 },
        { 105, 2 },
        { 187, 2 },
        { 45,  2 },
        { 59,  2 },
        { 38,  3 }
    },
    {
        { 189, 2 },
        { 192, 2 },
        { 193, 2 },
        { 194, 3 },
        { 200, 2 }
    },

}

SPECIES = {
    ["Wurmple"] = { "Wurmple", "Silcoon", "Beautifly" },
    ["Wurmple "] = { "Wurmple", "Silcoon", "Dustox" },
    ["Ralts"] = { "Ralts", "Kirlia", "Gardevoir" },
    ["Whismur"] = { "Whismur", "Loudred", "Exploud" },
    ["Zubat"] = { "Zubat", "Golbat", "Crobat" },
    ["Aron"] = { "Aron", "Lairon", "Aggron" },
    ["Oddishruby"] = { "Oddish", "Gloom", "Vileplume" },
    ["Oddishsapphire"] = { "Oddish", "Gloom", "Bellossom" },
    ["Spoink"] = { "Spoink", "Grumpig" },
    ["Shuppet"] = { "Shuppet", "Banette" },
    ["Chimecho"] = { "Chimecho" },
    ["Natu"] = { "Natu", "Xatu" },
    ["Sandshrew"] = { "Sandshrew", "Sandslash" },
    ["Spinda"] = { "Spinda" },
    ["Trapinch"] = { "Trapinch", "Vibrava", "Flygon" },
    ["Phanpy"] = { "Phanpy", "Donphan" },
    ["Snorunt"] = { "Snorunt", "Glalie" },
    ["Spheal"] = { "Spheal", "Sealeo", "Walrein" },
    ["Corsola"] = { "Corsola" },
    ["Horsea"] = { "Horsea", "Seadra", "Kingdra" },
    ["Bagon"] = { "Bagon", "Shelgon", "Salamence" },
    ["Lotad"] = { "Lotad", "Lombre", "Ludicolo" },
    ["Surskit"] = { "Surskit", "Masquerain" },
    ["Azurill"] = { "Azurill", "Marill", "Azumarill" },
    ["Gulpin"] = { "Gulpin", "Swalot" },
    ["Igglybuff"] = { "Igglybuff", "Jigglypuff", "Wigglytuff" },
    ["Chinchou"] = { "Chinchou", "Lanturn" },
    ["Seedot"] = { "Seedot", "Nuzleaf", "Shiftry" },
    ["Shroomish"] = { "Shroomish", "Breloom" },
    ["Skitty"] = { "Skitty", "Delcatty" },
    ["Plusle"] = { "Plusle" },
    ["Minun"] = { "Minun" },
    ["Wynaut"] = { "Wynaut", "Wobbuffet" },
    ["Zigzagoon"] = { "Zigzagoon", "Linoone" },
    ["Nuzleaf"] = { "Nuzleaf", "Shiftry" },
    ["Treecko"] = { "Treecko", "Grovyle", "Sceptile" },
    ["Numel"] = { "Numel", "Camerupt" },
    ["Slugma"] = { "Slugma", "Magcargo" },
    ["Torkoal"] = { "Torkoal" },
    ["Koffing"] = { "Koffing", "Weezing" },
    ["Skarmory"] = { "Skarmory" },
    ["Vulpix"] = { "Vulpix", "Ninetales" },
    ["Torchic"] = { "Torchic", "Combusken", "Blaziken" },
    ["Illumise"] = { "Illumise" },
    ["Zangoose"] = { "Zangoose" },
    ["Wailmer"] = { "Wailmer", "Wailord" },
    ["Lileep"] = { "Lileep", "Cradily" },
    ["Staryu"] = { "Staryu", "Starmie" },
    ["Doduo"] = { "Doduo", "Dodrio" },
    ["Psyduck"] = { "Psyduck", "Golduck" },
    ["Wobbuffet"] = { "Wobbuffet" },
    ["Girafarig"] = { "Girafarig" },
    ["Pinsir"] = { "Pinsir" },
    ["Heracross"] = { "Heracross" },
    ["Rhyhorn"] = { "Rhyhorn", "Rhydon" },
    ["Pikachu"] = { "Pikachu", "Raichu" },
    ["Pichu"] = { "Pichu", "Pikachu", "Raichu" },
    ["Mawile"] = { "Mawile" },
    ["Machop"] = { "Machop", "Machoke", "Machamp" },
    ["Solrock"] = { "Solrock" },
    ["Beldum"] = { "Beldum", "Metang", "Metagross" },
    ["Regirock"] = { "Regirock" },
    ["Regice"] = { "Regice" },
    ["Jirachi"] = { "Jirachi" },
    ["Registeel"] = { "Registeel" },
    ["Silcoon"] = { "Silcoon", "Beautifly" },
    ["Cascoon"] = { "Cascoon", "Dustox" },
    ["Slakoth"] = { "Slakoth", "Vigoroth", "Slaking" },
    ["Roselia"] = { "Roselia" },
    ["Kecleon"] = { "Kecleon" },
    ["Duskull"] = { "Duskull", "Dusclops" },
    ["Nincada"] = { "Nincada", "Ninjask", "Shedinja" },
    ["Tropius"] = { "Tropius" },
    ["Lombre"] = { "Lombre", "Ludicolo" },
    ["Goldeen"] = { "Goldeen", "Seaking" },
    ["Marill"] = { "Marill", "Azumarill" },
    ["Barboach"] = { "Barboach", "Whiscash" },
    ["Corphish"] = { "Corphish", "Crawdaunt" },
    ["Feebas"] = { "Feebas", "Milotic" },
    ["Mudkip"] = { "Mudkip", "Marshtomp", "Swampert" },
    ["Poochyena"] = { "Poochyena", "Mightyena" },
    ["Taillow"] = { "Taillow", "Swellow" },
    ["Electrike"] = { "Electrike", "Manectric" },
    ["Magnemite"] = { "Magnemite", "Magneton" },
    ["Voltorb"] = { "Voltorb", "Electrode" },
    ["Jigglypuff"] = { "Jigglypuff", "Wigglytuff" },
    ["Castform"] = { "Castform" },
    ["Volbeat"] = { "Volbeat" },
    ["Seviper"] = { "Seviper" },
    ["Wingull"] = { "Wingull", "Pelipper" },
    ["Magikarp"] = { "Magikarp", "Gyarados" },
    ["Tentacool"] = { "Tentacool", "Tentacruel" },
    ["Carvanha"] = { "Carvanha", "Sharpedo" },
    ["Anorith"] = { "Anorith", "Armaldo" },
    ["Luvdisc"] = { "Luvdisc" },
    ["Clamperl"] = { "Clamperl", "Huntail", "Gorebyss" },
    ["Relicanth"] = { "Relicanth" },
    ["Geodude"] = { "Geodude", "Graveler", "Golem" },
    ["Meditite"] = { "Meditite", "Medicham" },
    ["Vibrava"] = { "Vibrava", "Flygon" },
    ["Cacnea"] = { "Cacnea", "Cacturne" },
    ["Baltoy"] = { "Baltoy", "Claydol" },
    ["Absol"] = { "Absol" },
    ["Swablu"] = { "Swablu", "Altaria" },
    ["Loudred"] = { "Loudred", "Exploud" },
    ["Makuhita"] = { "Makuhita", "Hariyama" },
    ["Nosepass"] = { "Nosepass" },
    ["Grimer"] = { "Grimer", "Muk" },
    ["Lunatone"] = { "Lunatone" },
    ["Shelgon"] = { "Shelgon", "Salamence" },
    ["Abra"] = { "Abra", "Kadabra", "Alakazam" },
    ["Sableye"] = { "Sableye" },
    ["Aerodactyl"] = { "Aerodactyl" },
    ["Chikorita"] = { "Chikorita" },
    ["Totodile"] = { "Totodile" },
    ["Cyndaquil"] = { "Cyndaquil" },
    ["Latias"] = { "Latias" },
    ["Latios"] = { "Latios" },
    ["Rayquaza"] = { "Rayquaza" },
    ["Kyogre"] = { "Kyogre" },
    ["Groudon"] = { "Groudon" }
}


AREA_NAMES = {
    --  [1] = "forestR",
    --   [2] = "volcanoR",
    --   [3] = "plainsR",
    --   [4] = "oceanR",
    --  [5] = "safariR",
    --  [6] = "caveR",
    --  [7] = "ruinsR",
    --  [8] = "forestS",
    --  [9] = "lakeS",
    --  [10] = "plainsS",
    --  [11] = "wildernessS",
    -- [12] = "oceanS",
    --  [13] = "caveS",
    --  [14] = "ruinsS",
    -- [15] = "egg1",
    -- [16] = "egg2",
    --  [17] = "egg3",
    -- [18] = "egg4",
    -- [19] = "eggruby",
    -- [20] = "eggsapphire",
    [21] = "chiko",
    [22] = "toto",
    [23] = "guest",
    [24] = "ratecard",
    [25] = "get",
    -- [26] = "ruby",
    --   [27] = "sapphire",
    [28] = "ruinscard",
    [29] = "evo",
    [30] = "aero",
    [31] = "cynda",
    [32] = "startcoins",
    [33] = "startball",
    [34] = "perpichu",
    [35] = "exp",
    [36] = "leaf",
    [37] = "fire",
    [38] = "link",
    [39] = "moon",
    [40] = "water",
    [41] = "thunder",
    [42] = "sun",
    [43] = "friend",
    [44] = "block",
    [45] = "Difficulty",
    [46] = "Ool",
    [47] = "area",
    [48] = "egg",
    [49] = "bonus",
    [50] = "field",
    [51] = "evolutions"
}


AREA_NAMES_RUBY = {
    [1] = "forestR",
    [2] = "volcanoR",
    [3] = "plainsR",
    [4] = "oceanR",
    [5] = "safariR",
    [6] = "caveR",
    [7] = "ruinsR"
}


AREA_NAMES_SAPPHIRE = {

    [1] = "forestS",
    [2] = "lakeS",
    [3] = "plainsS",
    [4] = "wildernessS",
    [5] = "oceanS",
    [6] = "caveS",
    [7] = "ruinsS"
}


POKEMON_RUBY_AREA = {
    ["caveR"] = {
        { "Loudred",  2, false },
        { "Nosepass", 2, true },
        { "Mawile",   2, false },
        { "Machop",   2, false },
        { "Grimer",   2, false },
        { "Solrock",  2, false },
        { "Shelgon",  2, false },
        { "Abra",     3, false },
    },
    ["forestR"] = {
        { "Zigzagoon", 2, false },
        { "Silcoon",   2, false },
        { "Cascoon",   2, false },
        { "Nuzleaf",   2, false },
        { "Kecleon",   2, true },
        { "Duskull",   2, false },
        { "Treecko",   3, false },
        { "Nincada",   3, false },
    },
    ["oceanR"] = {
        { "Wingull",   2, false },
        { "Tentacool", 2, false },
        { "Carvanha",  2, false },
        { "Wailmer",   2, false },
        { "Lileep",    2, true },
        { "Luvdisc",   2, false },
        { "Staryu",    3, false },
        { "Relicanth", 3, false },
    },
    ["plainsR"] = {
        { "Poochyena", 2, false },
        { "Taillow",   2, false },
        { "Electrike", 2, false },
        { "Magnemite", 2, false },
        { "Voltorb",   2, false },
        { "Illumise",  2, false },
        { "Castform",  2, true },
        { "Zangoose",  3, false },
    },
    ["ruinsR"] = {
        { "Beldum",    2, false },
        { "Regirock",  2, false },
        { "Regice",    2, false },
        { "Jirachi",   2, false },
        { "Registeel", 3, false },
    },
    ["safariR"] = {
        { "Doduo",     2, false },
        { "Psyduck",   2, false },
        { "Wobbuffet", 2, true },
        { "Girafarig", 2, false },
        { "Pinsir",    2, false },
        { "Heracross", 2, false },
        { "Rhyhorn",   2, false },
        { "Pikachu",   3, false },
    },
    ["volcanoR"] = {
        { "Numel",    2, false },
        { "Slugma",   2, false },
        { "Torkoal",  2, false },
        { "Koffing",  2, false },
        { "Skarmory", 2, true },
        { "Vulpix",   2, false },
        { "Torchic",  3, false },
    },
}



POKEMON_SAPPHIRE_AREA = {

    ["caveS"] = {
        { "Loudred",  2, false },
        { "Makuhita", 2, false },
        { "Nosepass", 2, true },
        { "Grimer",   2, false },
        { "Lunatone", 2, false },
        { "Shelgon",  2, false },
        { "Abra",     3, false },
        { "Sableye",  3, false },
    },
    ["forestS"] = {
        { "Silcoon", 2, false },
        { "Cascoon", 2, false },
        { "Slakoth", 2, false },
        { "Roselia", 2, false },
        { "Kecleon", 2, true },
        { "Duskull", 2, false },
        { "Nincada", 3, false },
        { "Tropius", 3, false },
    },
    ["lakeS"] = {
        { "Lombre",   2, false },
        { "Goldeen",  2, false },
        { "Marill",   2, false },
        { "Barboach", 2, false },
        { "Corphish", 2, false },
        { "Feebas",   2, true },
        { "Mudkip",   3, false },
    },
    ["oceanS"] = {
        { "Wingull",   2, false },
        { "Magikarp",  2, false },
        { "Tentacool", 2, false },
        { "Carvanha",  2, false },
        { "Anorith",   2, true },
        { "Luvdisc",   2, false },
        { "Clamperl",  3, false },
        { "Relicanth", 3, false },
    },
    ["plainsS"] = {
        { "Poochyena",  2, false },
        { "Taillow",    2, false },
        { "Electrike",  2, false },
        { "Magnemite",  2, false },
        { "Voltorb",    2, false },
        { "Jigglypuff", 2, false },
        { "Castform",   2, true },
        { "Volbeat",    3, false },
        { "Seviper",    3, false },
    },
    ["ruinsS"] = {
        { "Beldum",    2, false },
        { "Regirock",  2, false },
        { "Regice",    2, false },
        { "Jirachi",   2, false },
        { "Registeel", 3, false },
    },
    ["wildernessS"] = {
        { "Geodude",  2, false },
        { "Meditite", 2, false },
        { "Vibrava",  2, false },
        { "Cacnea",   2, false },
        { "Baltoy",   2, false },
        { "Absol",    2, true },
        { "Swablu",   3, false },
    }
}


POKEMON_RUBY_EGG = {
    ["egg1"] = {
        { "Wurmple" },
        { "Wurmple " },
        { "Ralts" },
        { "Whismur" },
        { "Zubat" },
        { "Aron" }
    },

    ["egg2"] = {
        { "Oddish" },
        { "Spoink" },
        { "Shuppet" },
        { "Chimecho" },
        { "Natu" }
    },

    ["egg3"] = {
        { "Sandshrew" },
        { "Spinda" },
        { "Trapinch" },
        { "Phanpy" }
    },

    ["egg4"] = {
        { "Snorunt" },
        { "Spheal" },
        { "Corsola" },
        { "Horsea" },
        { "Bagon" }
    },

    ["eggruby"] = {
        { "Seedot" },
        { "Shroomish" },
        { "Skitty" },
        { "Plusle" },
        { "Minun" },
        { "Wynaut" }
    }

}

POKEMON_EGG = {
    ["Wurmple"] = true,
    ["Ralts"] = true,
    ["Whismur"] = true,
    ["Zubat"] = true,
    ["Aron"] = true,
    ["Oddish"] = true,
    ["Spoink"] = true,
    ["Shuppet"] = true,
    ["Chimecho"] = true,
    ["Natu"] = true,
    ["Sandshrew"] = true,
    ["Spinda"] = true,
    ["Trapinch"] = true,
    ["Phanpy"] = true,
    ["Snorunt"] = true,
    ["Spheal"] = true,
    ["Corsola"] = true,
    ["Horsea"] = true,
    ["Bagon"] = true,
    ["Lotad"] = true,
    ["Surskit"] = true,
    ["Azurill"] = true,
    ["Gulpin"] = true,
    ["Igglybuff"] = true,
    ["Chinchou"] = true,
    ["Seedot"] = true,
    ["Shroomish"] = true,
    ["Skitty"] = true,
    ["Plusle"] = true,
    ["Minun"] = true,
    ["Wynaut"] = true,
    ["Pichu"] = true


}



POKEMON_RUBY = {
    ["Loudred"] = { 2, false },
    ["Nosepass"] = { 2, true },
    ["Mawile"] = { 2, false },
    ["Machop"] = { 2, false },
    ["Grimer"] = { 2, false },
    ["Solrock"] = { 2, false },
    ["Shelgon"] = { 2, false },
    ["Abra"] = { 3, false },
    ["Zigzagoon"] = { 2, false },
    ["Silcoon"] = { 2, false },
    ["Cascoon"] = { 2, false },
    ["Nuzleaf"] = { 2, false },
    ["Kecleon"] = { 2, true },
    ["Duskull"] = { 2, false },
    ["Treecko"] = { 3, false },
    ["Nincada"] = { 3, false },
    ["Wingull"] = { 2, false },
    ["Tentacool"] = { 2, false },
    ["Carvanha"] = { 2, false },
    ["Wailmer"] = { 2, false },
    ["Lileep"] = { 2, true },
    ["Luvdisc"] = { 2, false },
    ["Staryu"] = { 3, false },
    ["Relicanth"] = { 3, false },
    ["Poochyena"] = { 2, false },
    ["Taillow"] = { 2, false },
    ["Electrike"] = { 2, false },
    ["Magnemite"] = { 2, false },
    ["Voltorb"] = { 2, false },
    ["Illumise"] = { 2, false },
    ["Castform"] = { 2, true },
    ["Zangoose"] = { 3, false },
    ["Beldum"] = { 2, false },
    ["Regirock"] = { 2, false },
    ["Regice"] = { 2, false },
    ["Jirachi"] = { 2, false },
    ["Registeel"] = { 3, false },
    ["Doduo"] = { 2, false },
    ["Psyduck"] = { 2, false },
    ["Wobbuffet"] = { 2, true },
    ["Girafarig"] = { 2, false },
    ["Pinsir"] = { 2, false },
    ["Heracross"] = { 2, false },
    ["Rhyhorn"] = { 2, false },
    ["Pikachu"] = { 3, false },
    ["Numel"] = { 2, false },
    ["Slugma"] = { 2, false },
    ["Torkoal"] = { 2, false },
    ["Koffing"] = { 2, false },
    ["Skarmory"] = { 2, true },
    ["Vulpix"] = { 2, false },
    ["Torchic"] = { 3, false },


}


POKEMON_SAPPHIRE = {
    ["Loudred"] = { 2, false },
    ["Makuhita"] = { 2, false },
    ["Nosepass"] = { 2, true },
    ["Grimer"] = { 2, false },
    ["Lunatone"] = { 2, false },
    ["Shelgon"] = { 2, false },
    ["Abra"] = { 3, false },
    ["Sableye"] = { 3, false },
    ["Silcoon"] = { 2, false },
    ["Cascoon"] = { 2, false },
    ["Slakoth"] = { 2, false },
    ["Roselia"] = { 2, false },
    ["Kecleon"] = { 2, true },
    ["Duskull"] = { 2, false },
    ["Nincada"] = { 3, false },
    ["Tropius"] = { 3, false },
    ["Lombre"] = { 2, false },
    ["Goldeen"] = { 2, false },
    ["Marill"] = { 2, false },
    ["Barboach"] = { 2, false },
    ["Corphish"] = { 2, false },
    ["Feebas"] = { 2, true },
    ["Mudkip"] = { 3, false },
    ["Wingull"] = { 2, false },
    ["Magikarp"] = { 2, false },
    ["Tentacool"] = { 2, false },
    ["Carvanha"] = { 2, false },
    ["Anorith"] = { 2, true },
    ["Luvdisc"] = { 2, false },
    ["Clamperl"] = { 3, false },
    ["Relicanth"] = { 3, false },
    ["Poochyena"] = { 2, false },
    ["Taillow"] = { 2, false },
    ["Electrike"] = { 2, false },
    ["Magnemite"] = { 2, false },
    ["Voltorb"] = { 2, false },
    ["Jigglypuff"] = { 2, false },
    ["Castform"] = { 2, true },
    ["Volbeat"] = { 3, false },
    ["Seviper"] = { 3, false },
    ["Beldum"] = { 2, false },
    ["Regirock"] = { 2, false },
    ["Regice"] = { 2, false },
    ["Jirachi"] = { 2, false },
    ["Registeel"] = { 3, false },
    ["Geodude"] = { 2, false },
    ["Meditite"] = { 2, false },
    ["Vibrava"] = { 2, false },
    ["Cacnea"] = { 2, false },
    ["Baltoy"] = { 2, false },
    ["Absol"] = { 2, true },
    ["Swablu"] = { 3, false }

}

POKEMON_EVO_RUBY = {
    ["Grovyle"] = { 1, "Treecko", false },
    ["Sceptile"] = { 1, "Grovyle", true },
    ["Combusken"] = { 1, "Torchic", false },
    ["Blaziken"] = { 1, "Combusken", true },
    ["Mightyena"] = { 1, "Poochyena", false },
    ["Linoone"] = { 1, "Zigzagoon", false },
    ["Beautifly"] = { 1, "Silcoon", false },
    ["Dustox"] = { 1, "Cascoon", false },
    ["Shiftry"] = { 2, "Nuzleaf", false },
    ["Swellow"] = { 1, "Taillow", false },
    ["Pelipper"] = { 1, "Wingull", false },
    ["Kadabra"] = { 1, "Abra", false },
    ["Alakazam"] = { 4, "Kadabra", true },
    ["Ninjask"] = { 1, "Nincada", false },
    ["Shedinja"] = { 1, "Nincada", false },
    ["Exploud"] = { 1, "Loudred", false },
    ["Tentacruel"] = { 1, "Tentacool", false },
    ["Machoke"] = { 1, "Machop", false },
    ["Machamp"] = { 4, "Machoke", true },
    ["Manectric"] = { 1, "Electrike", false },
    ["Magneton"] = { 1, "Magnemite", false },
    ["Electrode"] = { 1, "Voltorb", false },
    ["Dodrio"] = { 1, "Doduo", false },
    ["Sharpedo"] = { 1, "Carvanha", false },
    ["Wailord"] = { 1, "Wailmer", false },
    ["Camerupt"] = { 1, "Numel", false },
    ["Magcargo"] = { 1, "Slugma", false },
    ["Muk"] = { 1, "Grimer", false },
    ["Weezing"] = { 1, "Koffing", false },
    ["Cradily"] = { 1, "Lileep", false },
    ["Starmie"] = { 6, "Staryu", false },
    ["Dusclops"] = { 1, "Duskull", false },
    ["Ninetales"] = { 3, "Vulpix", false },
    ["Raichu"] = { 7, "Pikachu", false },
    ["Golduck"] = { 1, "Psyduck", false },
    ["Rhydon"] = { 1, "Rhyhorn", false },
    ["Salamence"] = { 1, "Shelgon", false },
    ["Metang"] = { 1, "Beldum", false },
    ["Metagross"] = { 1, "Metang", true },


}

POKEMON_EVO_SAPPHIRE = {
    ["Marshtomp"] = { 1, "Mudkip", false },
    ["Swampert"] = { 1, "Marshtomp", true },
    ["Mightyena"] = { 1, "Poochyena", false },
    ["Beautifly"] = { 1, "Silcoon", false },
    ["Dustox"] = { 1, "Cascoon", false },
    ["Ludicolo"] = { 6, "Lombre", false },
    ["Swellow"] = { 1, "Taillow", false },
    ["Pelipper"] = { 1, "Wingull", false },
    ["Vigoroth"] = { 1, "Slakoth", false },
    ["Slaking"] = { 1, "Vigoroth", true },
    ["Kadabra"] = { 1, "Abra", false },
    ["Alakazam"] = { 4, "Kadabra", true },
    ["Ninjask"] = { 1, "Nincada", false },
    ["Shedinja"] = { 1, "Nincada", false },
    ["Exploud"] = { 1, "Loudred", false },
    ["Hariyama"] = { 1, "Makuhita", false },
    ["Seaking"] = { 1, "Goldeen", false },
    ["Gyarados"] = { 1, "Magikarp", false },
    ["Azumarill"] = { 1, "Marill", false },
    ["Graveler"] = { 1, "Geodude", false },
    ["Golem"] = { 4, "Graveler", true },
    ["Tentacruel"] = { 1, "Tentacool", false },
    ["Medicham"] = { 1, "Meditite", false },
    ["Manectric"] = { 1, "Electrike", false },
    ["Magneton"] = { 1, "Magnemite", false },
    ["Electrode"] = { 1, "Voltorb", false },
    ["Sharpedo"] = { 1, "Carvanha", false },
    ["Muk"] = { 1, "Grimer", false },
    ["Flygon"] = { 1, "Vibrava", false },
    ["Cacturne"] = { 1, "Cacnea", false },
    ["Altaria"] = { 1, "Swablu", false },
    ["Whiscash"] = { 1, "Barboach", false },
    ["Crawdaunt"] = { 1, "Corphish", false },
    ["Claydol"] = { 1, "Baltoy", false },
    ["Armaldo"] = { 1, "Anorith", false },
    ["Wigglytuff"] = { 5, "Jigglypuff", false },
    ["Milotic"] = { 10, "Feebas", false },
    ["Dusclops"] = { 1, "Duskull", false },
    ["Huntail"] = { 4, "Clamperl", false },
    ["Gorebyss"] = { 4, "Clamperl", false },
    ["Salamence"] = { 1, "Shelgon", false },
    ["Metang"] = { 1, "Beldum", false },
    ["Metagross"] = { 1, "Metang", true },
}


POKEMON_EVO_RUBY_EGG = {
    ["Silcoon"] = { 1, "Wurmple", false },
    ["Cascoon"] = { 1, "Wurmple", false },
    ["Beautifly"] = { 1, "Silcoon", true },
    ["Dustox"] = { 1, "Cascoon", true },
    ["Nuzleaf"] = { 1, "Seedot", false },
    ["Shiftry"] = { 2, "Nuzleaf", true },
    ["Breloom"] = { 1, "Shroomish", false },
    ["Delcatty"] = { 5, "Skitty", false },
    ["Loudred"] = { 1, "Whismur", false },
    ["Exploud"] = { 1, "Loudred", true },
    ["Gloom"] = { 1, "Oddish", false },
    ["Vileplume"] = { 2, "Gloom", true },
    ["Grumpig"] = { 1, "Spoink", false },
    ["Sandslash"] = { 1, "Sandshrew", false },
    ["Vibrava"] = { 1, "Trapinch", false },
    ["Flygon"] = { 1, "Vibrava", true },
    ["Banette"] = { 1, "Shuppet", false },
    ["Pikachu"] = { 9, "Pichu", false },
    ["Raichu"] = { 7, "Pikachu", true },
    ["Wobbuffet"] = { 1, "Wynaut", false },
    ["Xatu"] = { 1, "Natu", false },
    ["Donphan"] = { 1, "Phanpy", false },
    ["Golbat"] = { 1, "Zubat", false },
    ["Crobat"] = { 9, "Golbat", true },
    ["Kirlia"] = { 1, "Ralts", false },
    ["Gardevoir"] = { 1, "Kirlia", true },
    ["Glalie"] = { 1, "Snorunt", false },
    ["Sealeo"] = { 1, "Spheal", false },
    ["Walrein"] = { 1, "Sealeo", true },
    ["Seadra"] = { 1, "Horsea", false },
    ["Kingdra"] = { 4, "Seadra", true },
    ["Shelgon"] = { 1, "Bagon", false },
    ["Salamence"] = { 1, "Shelgon", true },
    ["Lairon"] = { 1, "Aron", false },
    ["Aggron"] = { 1, "Lairon", true },

}


POKEMON_EVO_SAPPHIRE_EGG = {
    ["Silcoon"] = { 1, "Wurmple", false },
    ["Cascoon"] = { 1, "Wurmple", false },
    ["Beautifly"] = { 1, "Silcoon", true },
    ["Dustox"] = { 1, "Cascoon", true },
    ["Lombre"] = { 1, "Lotad", false },
    ["Ludicolo"] = { 6, "Lombre", true },
    ["Loudred"] = { 1, "Whismur", false },
    ["Exploud"] = { 1, "Loudred", true },
    ["Masquerain"] = { 1, "Surskit", false },
    ["Swalot"] = { 1, "Gulpin", false },
    ["Gloom"] = { 1, "Oddish", false },
    ["Bellossom"] = { 8, "Gloom", true },
    ["Marill"] = { 9, "Azurill", false },
    ["Azumarill"] = { 1, "Marill", true },
    ["Grumpig"] = { 1, "Spoink", false },
    ["Sandslash"] = { 1, "Sandshrew", false },
    ["Vibrava"] = { 1, "Trapinch", false },
    ["Flygon"] = { 1, "Vibrava", true },
    ["Jigglypuff"] = { 9, "Igglybuff", false },
    ["Wigglytuff"] = { 5, "Jigglypuff", true },
    ["Banette"] = { 1, "Shuppet", false },
    ["Pikachu"] = { 9, "Pichu", false },
    ["Raichu"] = { 7, "Pikachu", true },
    ["Xatu"] = { 1, "Natu", false },
    ["Donphan"] = { 1, "Phanpy", false },
    ["Golbat"] = { 1, "Zubat", false },
    ["Crobat"] = { 9, "Golbat", true },
    ["Kirlia"] = { 1, "Ralts", false },
    ["Gardevoir"] = { 1, "Kirlia", true },
    ["Glalie"] = { 1, "Snorunt", false },
    ["Sealeo"] = { 1, "Spheal", false },
    ["Walrein"] = { 1, "Sealeo", true },
    ["Lanturn"] = { 1, "Chinchou", false },
    ["Seadra"] = { 1, "Horsea", false },
    ["Kingdra"] = { 4, "Seadra", true },
    ["Shelgon"] = { 1, "Bagon", false },
    ["Salamence"] = { 1, "Shelgon", true },
    ["Lairon"] = { 1, "Aron", false },
    ["Aggron"] = { 1, "Lairon", true },
}


EVOLUTION_METHOD = {
    [1] = "exp",
    [2] = "leaf",
    [3] = "fire",
    [4] = "link",
    [5] = "moon",
    [6] = "water",
    [7] = "thunder",
    [8] = "sun",
    [9] = "friend",
    [10] = "block",
}



POKEMON_RUBY_LIST = {

    ["TreeckoRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Treecko",
    ["GrovyleRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Grovyle",
    ["SceptileRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Sceptile",
    ["TorchicRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Torchic",
    ["CombuskenRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Combusken",
    ["BlazikenRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Blaziken",
    ["PoochyenaRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Poochyena",
    ["MightyenaRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Mightyena",
    ["ZigzagoonRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Zigzagoon",
    ["LinooneRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Linoone",
    ["SilcoonRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Silcoon",
    ["BeautiflyRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Beautifly",
    ["CascoonRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Cascoon",
    ["DustoxRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Dustox",
    ["NuzleafRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Nuzleaf",
    ["ShiftryRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Shiftry",
    ["TaillowRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Taillow",
    ["SwellowRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Swellow",
    ["WingullRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Wingull",
    ["PelipperRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Pelipper",
    ["AbraRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Abra",
    ["KadabraRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Kadabra",
    ["AlakazamRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Alakazam",
    ["NincadaRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Nincada",
    ["NinjaskRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Ninjask",
    ["ShedinjaRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Shedinja",
    ["LoudredRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Loudred",
    ["ExploudRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Exploud",
    ["NosepassRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Nosepass",
    ["TentacoolRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Tentacool",
    ["TentacruelRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Tentacruel",
    ["MawileRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Mawile",
    ["MachopRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Machop",
    ["MachokeRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Machoke",
    ["MachampRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Machamp",
    ["ElectrikeRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Electrike",
    ["ManectricRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Manectric",
    ["MagnemiteRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Magnemite",
    ["MagnetonRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Magneton",
    ["VoltorbRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Voltorb",
    ["ElectrodeRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Electrode",
    ["IllumiseRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Illumise",
    ["DoduoRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Doduo",
    ["DodrioRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Dodrio",
    ["CarvanhaRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Carvanha",
    ["SharpedoRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Sharpedo",
    ["WailmerRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Wailmer",
    ["WailordRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Wailord",
    ["NumelRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Numel",
    ["CameruptRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Camerupt",
    ["SlugmaRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Slugma",
    ["MagcargoRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Magcargo",
    ["TorkoalRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Torkoal",
    ["GrimerRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Grimer",
    ["MukRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Muk",
    ["KoffingRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Koffing",
    ["WeezingRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Weezing",
    ["SkarmoryRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Skarmory",
    ["ZangooseRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Zangoose",
    ["SolrockRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Solrock",
    ["LileepRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Lileep",
    ["CradilyRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Cradily",
    ["CastformRuby"] = "@Ruby Board/Plains (Ruby)/Pokedex - Castform",
    ["StaryuRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Staryu",
    ["StarmieRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Starmie",
    ["KecleonRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Kecleon",
    ["DuskullRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Duskull",
    ["DusclopsRuby"] = "@Ruby Board/Forest (Ruby)/Pokedex - Dusclops",
    ["VulpixRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Vulpix",
    ["NinetalesRuby"] = "@Ruby Board/Volcano (Ruby)/Pokedex - Ninetales",
    ["PikachuRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Pikachu",
    ["RaichuRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Raichu",
    ["PsyduckRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Psyduck",
    ["GolduckRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Golduck",
    ["WobbuffetRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Wobbuffet",
    ["GirafarigRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Girafarig",
    ["PinsirRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Pinsir",
    ["HeracrossRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Heracross",
    ["RhyhornRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Rhyhorn",
    ["RhydonRuby"] = "@Ruby Board/Safari Zone (Ruby)/Pokedex - Rhydon",
    ["RelicanthRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Relicanth",
    ["LuvdiscRuby"] = "@Ruby Board/Ocean (Ruby)/Pokedex - Luvdisc",
    ["ShelgonRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Shelgon",
    ["SalamenceRuby"] = "@Ruby Board/Cave (Ruby)/Pokedex - Salamence",
    ["BeldumRuby"] = "@Ruby Board/Ruins (Ruby)/Pokedex - Beldum",
    ["MetangRuby"] = "@Ruby Board/Ruins (Ruby)/Pokedex - Metang",
    ["MetagrossRuby"] = "@Ruby Board/Ruins (Ruby)/Pokedex - Metagross",
    ["RegirockRuby"] = "@Ruby Board/Ruins (Ruby)/Pokedex - Regirock",
    ["RegiceRuby"] = "@Ruby Board/Ruins (Ruby)/Pokedex - Regice",
    ["RegisteelRuby"] = "@Ruby Board/Ruins (Ruby)/Pokedex - Registeel",
    ["GroudonRuby"] = "@Ruby Board/Special (Ruby)/Pokedex - Groudon",
    ["RayquazaRuby"] = "@Ruby Board/Special (Ruby)/Pokedex - Rayquaza",
    ["JirachiRuby"] = "@Ruby Board/Ruins (Ruby)/Pokedex - Jirachi",
    ["LatiosRuby"] = "@Special/Bonus Stage (Ruby)/Pokedex - Latios",
    ["ChikoritaRuby"] = "@Special/Bonus Stage (Ruby)/Pokedex - Chikorita",
    ["CyndaquilRuby"] = "@Special/Bonus Stage (Ruby)/Pokedex - Cyndaquil",
    ["TotodileRuby"] = "@Special/Bonus Stage (Ruby)/Pokedex - Totodile",
    ["AerodactylRuby"] = "@Special/Bonus Stage (Ruby)/Pokedex - Aerodactyl",
    ["WurmpleRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Wurmple",
    ["SilcoonRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Silcoon",
    ["BeautiflyRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Beautifly",
    ["CascoonRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Cascoon",
    ["DustoxRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Dustox",
    ["SeedotRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Seedot",
    ["NuzleafRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Nuzleaf",
    ["ShiftryRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Shiftry",
    ["RaltsRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Ralts",
    ["KirliaRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Kirlia",
    ["GardevoirRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Gardevoir",
    ["ShroomishRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Shroomish",
    ["BreloomRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Breloom",
    ["WhismurRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Whismur",
    ["LoudredRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Loudred",
    ["ExploudRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Exploud",
    ["SkittyRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Skitty",
    ["DelcattyRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Delcatty",
    ["ZubatRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Zubat",
    ["GolbatRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Golbat",
    ["CrobatRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Crobat",
    ["AronRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Aron",
    ["LaironRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Lairon",
    ["AggronRubyEgg"] = "@Eggs Ruby/Egg Bunch (1)/Pokedex - Aggron",
    ["PlusleRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Plusle",
    ["MinunRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Minun",
    ["OddishRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Oddish",
    ["GloomRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Gloom",
    ["VileplumeRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Vileplume",
    ["SpoinkRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Spoink",
    ["GrumpigRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Grumpig",
    ["SandshrewRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Sandshrew",
    ["SandslashRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Sandslash",
    ["SpindaRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Spinda",
    ["TrapinchRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Trapinch",
    ["VibravaRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Vibrava",
    ["FlygonRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Flygon",
    ["ShuppetRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Shuppet",
    ["BanetteRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Banette",
    ["ChimechoRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Chimecho",
    ["PichuRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Pichu",
    ["PikachuRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Pikachu",
    ["RaichuRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Raichu",
    ["WynautRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Wynaut",
    ["WobbuffetRubyEgg"] = "@Eggs Ruby/Egg Bunch (Ruby)/Pokedex - Wobbuffet",
    ["NatuRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Natu",
    ["XatuRubyEgg"] = "@Eggs Ruby/Egg Bunch (2)/Pokedex - Xatu",
    ["PhanpyRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Phanpy",
    ["DonphanRubyEgg"] = "@Eggs Ruby/Egg Bunch (3)/Pokedex - Donphan",
    ["SnoruntRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Snorunt",
    ["GlalieRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Glalie",
    ["SphealRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Spheal",
    ["SealeoRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Sealeo",
    ["WalreinRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Walrein",
    ["CorsolaRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Corsola",
    ["HorseaRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Horsea",
    ["SeadraRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Seadra",
    ["KingdraRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Kingdra",
    ["BagonRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Bagon",
    ["ShelgonRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Shelgon",
    ["SalamenceRubyEgg"] = "@Eggs Ruby/Egg Bunch (4)/Pokedex - Salamence",


}
POKEMON_SAPPHIRE_LIST = {

    ["MudkipSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Mudkip",
    ["MarshtompSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Marshtomp",
    ["SwampertSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Swampert",
    ["PoochyenaSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Poochyena",
    ["MightyenaSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Mightyena",
    ["SilcoonSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Silcoon",
    ["BeautiflySapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Beautifly",
    ["CascoonSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Cascoon",
    ["DustoxSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Dustox",
    ["LombreSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Lombre",
    ["LudicoloSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Ludicolo",
    ["TaillowSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Taillow",
    ["SwellowSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Swellow",
    ["WingullSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Wingull",
    ["PelipperSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Pelipper",
    ["SlakothSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Slakoth",
    ["VigorothSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Vigoroth",
    ["SlakingSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Slaking",
    ["AbraSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Abra",
    ["KadabraSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Kadabra",
    ["AlakazamSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Alakazam",
    ["NincadaSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Nincada",
    ["NinjaskSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Ninjask",
    ["ShedinjaSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Shedinja",
    ["LoudredSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Loudred",
    ["ExploudSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Exploud",
    ["MakuhitaSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Makuhita",
    ["HariyamaSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Hariyama",
    ["GoldeenSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Goldeen",
    ["SeakingSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Seaking",
    ["MagikarpSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Magikarp",
    ["GyaradosSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Gyarados",
    ["MarillSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Marill",
    ["AzumarillSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Azumarill",
    ["GeodudeSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Geodude",
    ["GravelerSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Graveler",
    ["GolemSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Golem",
    ["NosepassSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Nosepass",
    ["TentacoolSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Tentacool",
    ["TentacruelSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Tentacruel",
    ["SableyeSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Sableye",
    ["MedititeSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Meditite",
    ["MedichamSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Medicham",
    ["ElectrikeSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Electrike",
    ["ManectricSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Manectric",
    ["MagnemiteSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Magnemite",
    ["MagnetonSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Magneton",
    ["VoltorbSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Voltorb",
    ["ElectrodeSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Electrode",
    ["VolbeatSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Volbeat",
    ["RoseliaSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Roselia",
    ["CarvanhaSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Carvanha",
    ["SharpedoSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Sharpedo",
    ["GrimerSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Grimer",
    ["MukSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Muk",
    ["VibravaSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Vibrava",
    ["FlygonSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Flygon",
    ["CacneaSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Cacnea",
    ["CacturneSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Cacturne",
    ["SwabluSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Swablu",
    ["AltariaSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Altaria",
    ["SeviperSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Seviper",
    ["LunatoneSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Lunatone",
    ["BarboachSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Barboach",
    ["WhiscashSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Whiscash",
    ["CorphishSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Corphish",
    ["CrawdauntSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Crawdaunt",
    ["BaltoySapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Baltoy",
    ["ClaydolSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Claydol",
    ["AnorithSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Anorith",
    ["ArmaldoSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Armaldo",
    ["JigglypuffSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Jigglypuff",
    ["WigglytuffSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Wigglytuff",
    ["FeebasSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Feebas",
    ["MiloticSapphire"] = "@Sapphire Board/Lake (Sapphire)/Pokedex - Milotic",
    ["CastformSapphire"] = "@Sapphire Board/Plains (Sapphire)/Pokedex - Castform",
    ["KecleonSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Kecleon",
    ["DuskullSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Duskull",
    ["DusclopsSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Dusclops",
    ["TropiusSapphire"] = "@Sapphire Board/Forest (Sapphire)/Pokedex - Tropius",
    ["AbsolSapphire"] = "@Sapphire Board/Wilderness (Sapphire)/Pokedex - Absol",
    ["ClamperlSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Clamperl",
    ["HuntailSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Huntail",
    ["GorebyssSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Gorebyss",
    ["RelicanthSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Relicanth",
    ["LuvdiscSapphire"] = "@Sapphire Board/Ocean (Sapphire)/Pokedex - Luvdisc",
    ["ShelgonSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Shelgon",
    ["SalamenceSapphire"] = "@Sapphire Board/Cave (Sapphire)/Pokedex - Salamence",
    ["BeldumSapphire"] = "@Sapphire Board/Ruins (Sapphire)/Pokedex - Beldum",
    ["MetangSapphire"] = "@Sapphire Board/Ruins (Sapphire)/Pokedex - Metang",
    ["MetagrossSapphire"] = "@Sapphire Board/Ruins (Sapphire)/Pokedex - Metagross",
    ["RegirockSapphire"] = "@Sapphire Board/Ruins (Sapphire)/Pokedex - Regirock",
    ["RegiceSapphire"] = "@Sapphire Board/Ruins (Sapphire)/Pokedex - Regice",
    ["RegisteelSapphire"] = "@Sapphire Board/Ruins (Sapphire)/Pokedex - Registeel",
    ["KyogreSapphire"] = "@Sapphire Board/Special (Sapphire)/Pokedex - Kyogre",
    ["RayquazaSapphire"] = "@Sapphire Board/Special (Sapphire)/Pokedex - Rayquaza",
    ["JirachiSapphire"] = "@Sapphire Board/Ruins (Sapphire)/Pokedex - Jirachi",
    ["LatiasSapphire"] = "@Special/Bonus Stage (Sapphire)/Pokedex - Latias",
    ["ChikoritaSapphire"] = "@Special/Bonus Stage (Sapphire)/Pokedex - Chikorita",
    ["CyndaquilSapphire"] = "@Special/Bonus Stage (Sapphire)/Pokedex - Cyndaquil",
    ["TotodileSapphire"] = "@Special/Bonus Stage (Sapphire)/Pokedex - Totodile",
    ["AerodactylSapphire"] = "@Special/Bonus Stage (Sapphire)/Pokedex - Aerodactyl",
    ["WurmpleSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Wurmple",
    ["SilcoonSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Silcoon",
    ["BeautiflySapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Beautifly",
    ["CascoonSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Cascoon",
    ["DustoxSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Dustox",
    ["LotadSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Lotad",
    ["LombreSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Lombre",
    ["LudicoloSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Ludicolo",
    ["RaltsSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Ralts",
    ["KirliaSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Kirlia",
    ["GardevoirSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Gardevoir",
    ["SurskitSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Surskit",
    ["MasquerainSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Masquerain",
    ["WhismurSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Whismur",
    ["LoudredSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Loudred",
    ["ExploudSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Exploud",
    ["AzurillSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Azurill",
    ["MarillSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Marill",
    ["AzumarillSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Azumarill",
    ["ZubatSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Zubat",
    ["GolbatSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Golbat",
    ["CrobatSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Crobat",
    ["AronSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Aron",
    ["LaironSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Lairon",
    ["AggronSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (1)/Pokedex - Aggron",
    ["OddishSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Oddish",
    ["GloomSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Gloom",
    ["BellossomSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Bellossom",
    ["GulpinSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Gulpin",
    ["SwalotSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Swalot",
    ["SpoinkSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Spoink",
    ["GrumpigSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Grumpig",
    ["SandshrewSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Sandshrew",
    ["SandslashSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Sandslash",
    ["SpindaSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Spinda",
    ["TrapinchSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Trapinch",
    ["VibravaSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Vibrava",
    ["FlygonSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Flygon",
    ["IgglybuffSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Igglybuff",
    ["JigglypuffSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Jigglypuff",
    ["WigglytuffSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Wigglytuff",
    ["ShuppetSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Shuppet",
    ["BanetteSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Banette",
    ["ChimechoSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Chimecho",
    ["PichuSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Pichu",
    ["PikachuSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Pikachu",
    ["RaichuSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Raichu",
    ["NatuSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Natu",
    ["XatuSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (2)/Pokedex - Xatu",
    ["PhanpySapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Phanpy",
    ["DonphanSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (3)/Pokedex - Donphan",
    ["SnoruntSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Snorunt",
    ["GlalieSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Glalie",
    ["SphealSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Spheal",
    ["SealeoSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Sealeo",
    ["WalreinSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Walrein",
    ["CorsolaSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Corsola",
    ["ChinchouSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Chinchou",
    ["LanturnSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (Sapphire)/Pokedex - Lanturn",
    ["HorseaSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Horsea",
    ["SeadraSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Seadra",
    ["KingdraSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Kingdra",
    ["BagonSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Bagon",
    ["ShelgonSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Shelgon",
    ["SalamenceSapphireEgg"] = "@Eggs Sapphire/Egg Bunch (4)/Pokedex - Salamence",


}


LOCATION_RUBY_LIST = {

    [1049] = "@Ruby Board/Makuhita/Ball Upgrade 1-25",
    [1050] = "@Ruby Board/Makuhita/Ball Upgrade 26-75",
    [1100] = "@Ruby Board/Makuhita/Ball Upgrade 76-99",
    [769] = "@Ruby Board/Ruby/Ball Upgrade 1-10",
    [779] = "@Ruby Board/Ruby/Ball Upgrade 11-25",
    [794] = "@Ruby Board/Ruby/Ball Upgrade 26-75",
    [844] = "@Ruby Board/Ruby/Ball Upgrade 76-99",
    [522] = "@Ruby Board/Ruby Board/Bonus Multiplier 1-10",
    [523] = "@Ruby Board/Ruby Board/Bonus Multiplier 11-25",
    [538] = "@Ruby Board/Ruby Board/Bonus Multiplier 26-75",
    [588] = "@Ruby Board/Ruby Board/Bonus Multiplier 76-99",
    [257] = "@Special/Bonus Stage (Ruby)/Kecleon Bonus Stage",
    [259] = "@Special/Bonus Stage (Ruby)/Groudon Bonus Stage",
    [260] = "@Special/Bonus Stage (Ruby)/Rayquaza Bonus Stage",
    [261] = "@Ruby Board/Spheal Bonus Stage (Ruby)/5 Poke Ball Hoops",
    [262] = "@Ruby Board/Spheal Bonus Stage (Ruby)/5 Spheal Hoops",
    [263] = "@Ruby Board/Spheal Bonus Stage (Ruby)/10 Combined Hoops",
}

LOCATION_SAPPHIRE_LIST = {
    [262] = "@Sapphire Board/Spheal Bonus Stage (Sapphire)/5 Spheal Hoops",
    [263] = "@Sapphire Board/Spheal Bonus Stage (Sapphire)/10 Combined Hoops",
    [261] = "@Sapphire Board/Spheal Bonus Stage (Sapphire)/5 Poke Ball Hoops",
    [260] = "@Special/Bonus Stage (Sapphire)/Rayquaza Bonus Stage",
    [258] = "@Special/Bonus Stage (Sapphire)/Kyogre Bonus Stage",
    [256] = "@Special/Bonus Stage (Sapphire)/Dusclops Bonus Stage",
    [613] = "@Sapphire Board/Sapphire Board/Bonus Multiplier 1-10",
    [623] = "@Sapphire Board/Sapphire Board/Bonus Multiplier 11-25",
    [638] = "@Sapphire Board/Sapphire Board/Bonus Multiplier 26-75",
    [688] = "@Sapphire Board/Sapphire Board/Bonus Multiplier 76-99",
    [869] = "@Sapphire Board/Sapphire/Ball Upgrade 1-10",
    [879] = "@Sapphire Board/Sapphire/Ball Upgrade 11-25",
    [894] = "@Sapphire Board/Sapphire/Ball Upgrade 26-75",
    [944] = "@Sapphire Board/Sapphire/Ball Upgrade 76-99",
}

LISTINGS = {
    [1] = "Treecko",
    [2] = "Grovyle",
    [3] = "Sceptile",
    [4] = "Torchic",
    [5] = "Combusken",
    [6] = "Blaziken",
    [7] = "Poochyena",
    [8] = "Mightyena",
    [9] = "Zigzagoon",
    [10] = "Linoone",
    [11] = "Silcoon",
    [12] = "Beautifly",
    [13] = "Cascoon",
    [14] = "Dustox",
    [15] = "Nuzleaf",
    [16] = "Shiftry",
    [17] = "Taillow",
    [18] = "Swellow",
    [19] = "Wingull",
    [20] = "Pelipper",
    [21] = "Abra",
    [22] = "Kadabra",
    [23] = "Alakazam",
    [24] = "Nincada",
    [25] = "Ninjask",
    [26] = "Shedinja",
    [27] = "Loudred",
    [28] = "Exploud",
    [29] = "Nosepass",
    [30] = "Tentacool",
    [31] = "Tentacruel",
    [32] = "Mawile",
    [33] = "Machop",
    [34] = "Machoke",
    [35] = "Machamp",
    [36] = "Electrike",
    [37] = "Manectric",
    [38] = "Magnemite",
    [39] = "Magneton",
    [40] = "Voltorb",
    [41] = "Electrode",
    [42] = "Illumise",
    [43] = "Doduo",
    [44] = "Dodrio",
    [45] = "Carvanha",
    [46] = "Sharpedo",
    [47] = "Wailmer",
    [48] = "Wailord",
    [49] = "Numel",
    [50] = "Camerupt",
    [51] = "Slugma",
    [52] = "Magcargo",
    [53] = "Torkoal",
    [54] = "Grimer",
    [55] = "Muk",
    [56] = "Koffing",
    [57] = "Weezing",
    [58] = "Skarmory",
    [59] = "Zangoose",
    [60] = "Solrock",
    [61] = "Lileep",
    [62] = "Cradily",
    [63] = "Castform",
    [64] = "Staryu",
    [65] = "Starmie",
    [66] = "Kecleon",
    [67] = "Duskull",
    [68] = "Dusclops",
    [69] = "Vulpix",
    [70] = "Ninetales",
    [71] = "Pikachu",
    [72] = "Raichu",
    [73] = "Psyduck",
    [74] = "Golduck",
    [75] = "Wobbuffet",
    [76] = "Girafarig",
    [77] = "Pinsir",
    [78] = "Heracross",
    [79] = "Rhyhorn",
    [80] = "Rhydon",
    [81] = "Relicanth",
    [82] = "Luvdisc",
    [83] = "Shelgon",
    [84] = "Salamence",
    [85] = "Beldum",
    [86] = "Metang",
    [87] = "Metagross",
    [88] = "Regirock",
    [89] = "Regice",
    [90] = "Registeel",
    [91] = "Groudon",
    [92] = "Rayquaza",
    [93] = "Jirachi",
    [94] = "Latios",
    [95] = "ChikoritaS",
    [96] = "Cyndaquil",
    [97] = "Totodile",
    [98] = "Aerodactyl",
    [99] = "Wurmple",
    [100] = "Silcoon",
    [101] = "Beautifly",
    [102] = "Cascoon",
    [103] = "Dustox",
    [104] = "Seedot",
    [105] = "Nuzleaf",
    [106] = "Shiftry",
    [107] = "Ralts",
    [108] = "Kirlia",
    [109] = "Gardevoir",
    [110] = "Shroomish",
    [111] = "Breloom",
    [112] = "Whismur",
    [113] = "Loudred",
    [114] = "Exploud",
    [115] = "Skitty",
    [116] = "Delcatty",
    [117] = "Zubat",
    [118] = "Golbat",
    [119] = "Crobat",
    [120] = "Aron",
    [121] = "Lairon",
    [122] = "Aggron",
    [123] = "Plusle",
    [124] = "Minun",
    [125] = "Oddish",
    [126] = "Gloom",
    [127] = "Vileplume",
    [128] = "Spoink",
    [129] = "Grumpig",
    [130] = "Sandshrew",
    [131] = "Sandslash",
    [132] = "Spinda",
    [133] = "Trapinch",
    [134] = "Vibrava",
    [135] = "Flygon",
    [136] = "Shuppet",
    [137] = "Banette",
    [138] = "Chimecho",
    [139] = "Pichu",
    [140] = "Pikachu",
    [141] = "Raichu",
    [142] = "Wynaut",
    [143] = "Wobbuffet",
    [144] = "Natu",
    [145] = "Xatu",
    [146] = "Phanpy",
    [147] = "Donphan",
    [148] = "Snorunt",
    [149] = "Glalie",
    [150] = "Spheal",
    [151] = "Sealeo",
    [152] = "Walrein",
    [153] = "Corsola",
    [154] = "Horsea",
    [155] = "Seadra",
    [156] = "Kingdra",
    [157] = "Bagon",
    [158] = "Shelgon",
    [159] = "Salamence",
    [160] = "Mudkip",
    [161] = "Marshtomp",
    [162] = "Swampert",
    [163] = "Poochyena",
    [164] = "Mightyena",
    [165] = "Silcoon",
    [166] = "Beautifly",
    [167] = "Cascoon",
    [168] = "Dustox",
    [169] = "Lombre",
    [170] = "Ludicolo",
    [171] = "Taillow",
    [172] = "Swellow",
    [173] = "Wingull",
    [174] = "Pelipper",
    [175] = "Slakoth",
    [176] = "Vigoroth",
    [177] = "Slaking",
    [178] = "Abra",
    [179] = "Kadabra",
    [180] = "Alakazam",
    [181] = "Nincada",
    [182] = "Ninjask",
    [183] = "Shedinja",
    [184] = "Loudred",
    [185] = "Exploud",
    [186] = "Makuhita",
    [187] = "Hariyama",
    [188] = "Goldeen",
    [189] = "Seaking",
    [190] = "Magikarp",
    [191] = "Gyarados",
    [192] = "Marill",
    [193] = "Azumarill",
    [194] = "Geodude",
    [195] = "Graveler",
    [196] = "Golem",
    [197] = "Nosepass",
    [198] = "Tentacool",
    [199] = "Tentacruel",
    [200] = "Sableye",
    [201] = "Meditite",
    [202] = "Medicham",
    [203] = "Electrike",
    [204] = "Manectric",
    [205] = "Magnemite",
    [206] = "Magneton",
    [207] = "Voltorb",
    [208] = "Electrode",
    [209] = "Volbeat",
    [210] = "Roselia",
    [211] = "Carvanha",
    [212] = "Sharpedo",
    [213] = "Grimer",
    [214] = "Muk",
    [215] = "Vibrava",
    [216] = "Flygon",
    [217] = "Cacnea",
    [218] = "Cacturne",
    [219] = "Swablu",
    [220] = "Altaria",
    [221] = "Seviper",
    [222] = "Lunatone",
    [223] = "Barboach",
    [224] = "Whiscash",
    [225] = "Corphish",
    [226] = "Crawdaunt",
    [227] = "Baltoy",
    [228] = "Claydol",
    [229] = "Anorith",
    [230] = "Armaldo",
    [231] = "Jigglypuff",
    [232] = "Wigglytuff",
    [233] = "Feebas",
    [234] = "Milotic",
    [235] = "Castform",
    [236] = "Kecleon",
    [237] = "Duskull",
    [238] = "Dusclops",
    [239] = "Tropius",
    [240] = "Absol",
    [241] = "Clamperl",
    [242] = "Huntail",
    [243] = "Gorebyss",
    [244] = "Relicanth",
    [245] = "Luvdisc",
    [246] = "Shelgon",
    [247] = "Salamence",
    [248] = "Beldum",
    [249] = "Metang",
    [250] = "Metagross",
    [251] = "Regirock",
    [252] = "Regice",
    [253] = "Registeel",
    [254] = "Kyogre",
    [255] = "Rayquaza",
    [256] = "Jirachi",
    [257] = "Latias",
    [258] = "Chikorita",
    [259] = "Cyndaquil",
    [260] = "Totodile",
    [261] = "Aerodactyl",
    [262] = "Wurmple",
    [263] = "Silcoon",
    [264] = "Beautifly",
    [265] = "Cascoon",
    [266] = "Dustox",
    [267] = "Lotad",
    [268] = "Lombre",
    [269] = "Ludicolo",
    [270] = "Ralts",
    [271] = "Kirlia",
    [272] = "Gardevoir",
    [273] = "Surskit",
    [274] = "Masquerain",
    [275] = "Whismur",
    [276] = "Loudred",
    [277] = "Exploud",
    [278] = "Azurill",
    [279] = "Marill",
    [280] = "Azumarill",
    [281] = "Zubat",
    [282] = "Golbat",
    [283] = "Crobat",
    [284] = "Aron",
    [285] = "Lairon",
    [286] = "Aggron",
    [287] = "Oddish",
    [288] = "Gloom",
    [289] = "Bellossom",
    [290] = "Gulpin",
    [291] = "Swalot",
    [292] = "Spoink",
    [293] = "Grumpig",
    [294] = "Sandshrew",
    [295] = "Sandslash",
    [296] = "Spinda",
    [297] = "Trapinch",
    [298] = "Vibrava",
    [299] = "Flygon",
    [300] = "Igglybuff",
    [301] = "Jigglypuff",
    [302] = "Wigglytuff",
    [303] = "Shuppet",
    [304] = "Banette",
    [305] = "Chimecho",
    [306] = "Pichu",
    [307] = "Pikachu",
    [308] = "Raichu",
    [309] = "Natu",
    [310] = "Xatu",
    [311] = "Phanpy",
    [312] = "Donphan",
    [313] = "Snorunt",
    [314] = "Glalie",
    [315] = "Spheal",
    [316] = "Sealeo",
    [317] = "Walrein",
    [318] = "Corsola",
    [319] = "Chinchou",
    [320] = "Lanturn",
    [321] = "Horsea",
    [322] = "Seadra",
    [323] = "Kingdra",
    [324] = "Bagon",
    [325] = "Shelgon",
    [326] = "Salamence",

}


OPTIONS_NUM = {
    "pokedex_requirement",
    "score_requirement",
    "bonus_multiplier_checks",
    "ball_upgrade_checks"
}

POKEMON_CODES = {
    [1] = { "TreeckoRuby", "Treecko" },
    [2] = { "GrovyleRuby", "Grovyle" },
    [3] = { "SceptileRuby", "Sceptile" },
    [4] = { "TorchicRuby", "Torchic" },
    [5] = { "CombuskenRuby", "Combusken" },
    [6] = { "BlazikenRuby", "Blaziken" },
    [7] = { "MudkipSapphire", "Mudkip" },
    [8] = { "MarshtompSapphire", "Marshtomp" },
    [9] = { "SwampertSapphire", "Swampert" },
    [10] = { "PoochyenaSapphire", "PoochyenaRuby", "Poochyena" },
    [11] = { "MightyenaSapphire", "MightyenaRuby", "Mightyena" },
    [12] = { "ZigzagoonRuby", "Zigzagoon" },
    [13] = { "LinooneRuby", "Linoone" },
    [14] = { "WurmpleRubyEgg", "WurmpleSapphireEgg", "Wurmple" },
    [15] = { "SilcoonSapphire", "SilcoonRuby", "SilcoonRubyEgg", "SilcoonSapphireEgg", "Silcoon" },
    [16] = { "BeautiflySapphire", "BeautiflyRuby", "BeautiflyRubyEgg", "BeautiflySapphireEgg", "Beautifly" },
    [17] = { "CascoonSapphire", "CascoonRuby", "CascoonRubyEgg", "CascoonSapphireEgg", "Cascoon" },
    [18] = { "DustoxSapphire", "DustoxRuby", "DustoxRubyEgg", "DustoxSapphireEgg", "Dustox" },
    [19] = { "LotadSapphireEgg", "Lotad" },
    [20] = { "LombreSapphire", "LombreSapphireEgg", "Lombre" },
    [21] = { "LudicoloSapphire", "LudicoloSapphireEgg", "Ludicolo" },
    [22] = { "SeedotRubyEgg", "Seedot" },
    [23] = { "NuzleafRuby", "NuzleafRubyEgg", "Nuzleaf" },
    [24] = { "ShiftryRuby", "ShiftryRubyEgg", "Shiftry" },
    [25] = { "TaillowSapphire", "TaillowRuby", "Taillow" },
    [26] = { "SwellowSapphire", "SwellowRuby", "Swellow" },
    [27] = { "WingullSapphire", "WingullRuby", "Wingull" },
    [28] = { "PelipperSapphire", "PelipperRuby", "Pelipper" },
    [29] = { "RaltsRubyEgg", "RaltsSapphireEgg", "Ralts" },
    [30] = { "KirliaRubyEgg", "KirliaSapphireEgg", "Kirlia" },
    [31] = { "GardevoirRubyEgg", "GardevoirSapphireEgg", "Gardevoir" },
    [32] = { "SurskitSapphireEgg", "Surskit" },
    [33] = { "MasquerainSapphireEgg", "Masquerain" },
    [34] = { "ShroomishRubyEgg", "Shroomish" },
    [35] = { "BreloomRubyEgg", "Breloom" },
    [36] = { "SlakothSapphire", "Slakoth" },
    [37] = { "VigorothSapphire", "Vigoroth" },
    [38] = { "SlakingSapphire", "Slaking" },
    [39] = { "AbraSapphire", "AbraRuby", "Abra" },
    [40] = { "KadabraSapphire", "KadabraRuby", "Kadabra" },
    [41] = { "AlakazamSapphire", "AlakazamRuby", "Alakazam" },
    [42] = { "NincadaSapphire", "NincadaRuby", "Nincada" },
    [43] = { "NinjaskSapphire", "NinjaskRuby", "Ninjask" },
    [44] = { "ShedinjaSapphire", "ShedinjaRuby", "Shedinja" },
    [45] = { "WhismurRubyEgg", "WhismurSapphireEgg", "Whismur" },
    [46] = { "LoudredRuby", "LoudredRubyEgg", "LoudredSapphireEgg", "LoudredSapphire", "Loudred" },
    [47] = { "ExploudRuby", "ExploudRubyEgg", "ExploudSapphireEgg", "ExploudSapphire", "Exploud" },
    [48] = { "MakuhitaSapphire", "Makuhita" },
    [49] = { "HariyamaSapphire", "Hariyama" },
    [50] = { "GoldeenSapphire", "Goldeen" },
    [51] = { "SeakingSapphire", "Seaking" },
    [52] = { "MagikarpSapphire", "Magikarp" },
    [53] = { "GyaradosSapphire", "Gyarados" },
    [54] = { "AzurillSapphireEgg", "Azurill" },
    [55] = { "MarillSapphire", "MarillSapphireEgg", "Marill" },
    [56] = { "AzumarillSapphire", "AzumarillSapphireEgg", "Azumarill" },
    [57] = { "GeodudeSapphire", "Geodude" },
    [58] = { "GravelerSapphire", "Graveler" },
    [59] = { "GolemSapphire", "Golem" },
    [60] = { "NosepassSapphire", "NosepassRuby", "Nosepass" },
    [61] = { "SkittyRubyEgg", "Skitty" },
    [62] = { "DelcattyRubyEgg", "Delcatty" },
    [63] = { "ZubatRubyEgg", "ZubatSapphireEgg", "Zubat" },
    [64] = { "GolbatRubyEgg", "GolbatSapphireEgg", "Golbat" },
    [65] = { "CrobatRubyEgg", "CrobatSapphireEgg", "Crobat" },
    [66] = { "TentacoolSapphire", "TentacoolRuby", "Tentacool" },
    [67] = { "TentacruelSapphire", "TentacruelRuby", "Tentacruel" },
    [68] = { "SableyeSapphire", "Sableye" },
    [69] = { "MawileRuby", "Mawile" },
    [70] = { "AronRubyEgg", "AronSapphireEgg", "Aron" },
    [71] = { "LaironRubyEgg", "LaironSapphireEgg", "Lairon" },
    [72] = { "AggronRubyEgg", "AggronSapphireEgg", "Aggron" },
    [73] = { "MachopRuby", "Machop" },
    [74] = { "MachokeRuby", "Machoke" },
    [75] = { "MachampRuby", "Machamp" },
    [76] = { "MedititeSapphire", "Meditite" },
    [77] = { "MedichamSapphire", "Medicham" },
    [78] = { "ElectrikeSapphire", "ElectrikeRuby", "Electrike" },
    [79] = { "ManectricSapphire", "ManectricRuby", "Manectric" },
    [80] = { "PlusleRubyEgg", "Plusle" },
    [81] = { "MinunRubyEgg", "Minun" },
    [82] = { "MagnemiteSapphire", "MagnemiteRuby", "Magnemite" },
    [83] = { "MagnetonSapphire", "MagnetonRuby", "Magneton" },
    [84] = { "VoltorbSapphire", "VoltorbRuby", "Voltorb" },
    [85] = { "ElectrodeSapphire", "ElectrodeRuby", "Electrode" },
    [86] = { "VolbeatSapphire", "Volbeat" },
    [87] = { "IllumiseRuby", "Illumise" },
    [88] = { "OddishRubyEgg", "OddishSapphireEgg", "Oddish" },
    [89] = { "GloomRubyEgg", "GloomSapphireEgg", "Gloom" },
    [90] = { "VileplumeRubyEgg", "Vileplume" },
    [91] = { "BellossomSapphireEgg", "Bellossom" },
    [92] = { "DoduoRuby", "Doduo" },
    [93] = { "DodrioRuby", "Dodrio" },
    [94] = { "RoseliaSapphire", "Roselia" },
    [95] = { "GulpinSapphireEgg", "Gulpin" },
    [96] = { "SwalotSapphireEgg", "Swalot" },
    [97] = { "CarvanhaSapphire", "CarvanhaRuby", "Carvanha" },
    [98] = { "SharpedoSapphire", "SharpedoRuby", "Sharpedo" },
    [99] = { "WailmerRuby", "Wailmer" },
    [100] = { "WailordRuby", "Wailord" },
    [101] = { "NumelRuby", "Numel" },
    [102] = { "CameruptRuby", "Camerupt" },
    [103] = { "SlugmaRuby", "Slugma" },
    [104] = { "MagcargoRuby", "Magcargo" },
    [105] = { "TorkoalRuby", "Torkoal" },
    [106] = { "GrimerSapphire", "GrimerRuby", "Grimer" },
    [107] = { "MukSapphire", "MukRuby", "Muk" },
    [108] = { "KoffingRuby", "Koffing" },
    [109] = { "WeezingRuby", "Weezing" },
    [110] = { "SpoinkRubyEgg", "SpoinkSapphireEgg", "Spoink" },
    [111] = { "GrumpigRubyEgg", "GrumpigSapphireEgg", "Grumpig" },
    [112] = { "SandshrewRubyEgg", "SandshrewSapphireEgg", "Sandshrew" },
    [113] = { "SandslashRubyEgg", "SandslashSapphireEgg", "Sandslash" },
    [114] = { "SpindaRubyEgg", "SpindaSapphireEgg", "Spinda" },
    [115] = { "SkarmoryRuby", "Skarmory" },
    [116] = { "TrapinchRubyEgg", "TrapinchSapphireEgg", "Trapinch" },
    [117] = { "VibravaSapphire", "VibravaRubyEgg", "VibravaSapphireEgg", "Vibrava" },
    [118] = { "FlygonSapphire", "FlygonRubyEgg", "FlygonSapphireEgg", "Flygon" },
    [119] = { "CacneaSapphire", "Cacnea" },
    [120] = { "CacturneSapphire", "Cacturne" },
    [121] = { "SwabluSapphire", "Swablu" },
    [122] = { "AltariaSapphire", "Altaria" },
    [123] = { "ZangooseRuby", "Zangoose" },
    [124] = { "SeviperSapphire", "Seviper" },
    [125] = { "LunatoneSapphire", "Lunatone" },
    [126] = { "SolrockRuby", "Solrock" },
    [127] = { "BarboachSapphire", "Barboach" },
    [128] = { "WhiscashSapphire", "Whiscash" },
    [129] = { "CorphishSapphire", "Corphish" },
    [130] = { "CrawdauntSapphire", "Crawdaunt" },
    [131] = { "BaltoySapphire", "Baltoy" },
    [132] = { "ClaydolSapphire", "Claydol" },
    [133] = { "LileepRuby", "Lileep" },
    [134] = { "CradilyRuby", "Cradily" },
    [135] = { "AnorithSapphire", "Anorith" },
    [136] = { "ArmaldoSapphire", "Armaldo" },
    [137] = { "IgglybuffSapphireEgg", "Igglybuff" },
    [138] = { "JigglypuffSapphire", "JigglypuffSapphireEgg", "Jigglypuff" },
    [139] = { "WigglytuffSapphire", "WigglytuffSapphireEgg", "Wigglytuff" },
    [140] = { "FeebasSapphire", "Feebas" },
    [141] = { "MiloticSapphire", "Milotic" },
    [142] = { "CastformSapphire", "CastformRuby", "Castform" },
    [143] = { "StaryuRuby", "Staryu" },
    [144] = { "StarmieRuby", "Starmie" },
    [145] = { "KecleonSapphire", "KecleonRuby", "Kecleon" },
    [146] = { "ShuppetRubyEgg", "ShuppetSapphireEgg", "Shuppet" },
    [147] = { "BanetteRubyEgg", "BanetteSapphireEgg", "Banette" },
    [148] = { "DuskullSapphire", "DuskullRuby", "Duskull" },
    [149] = { "DusclopsSapphire", "DusclopsRuby", "Dusclops" },
    [150] = { "TropiusSapphire", "Tropius" },
    [151] = { "ChimechoRubyEgg", "ChimechoSapphireEgg", "Chimecho" },
    [152] = { "AbsolSapphire", "Absol" },
    [153] = { "VulpixRuby", "Vulpix" },
    [154] = { "NinetalesRuby", "Ninetales" },
    [155] = { "PichuRubyEgg", "PichuSapphireEgg", "Pichu" },
    [156] = { "PikachuRuby", "PikachuRubyEgg", "PikachuSapphireEgg", "Pikachu" },
    [157] = { "RaichuRuby", "RaichuRubyEgg", "RaichuSapphireEgg", "Raichu" },
    [158] = { "PsyduckRuby", "Psyduck" },
    [159] = { "GolduckRuby", "Golduck" },
    [160] = { "WynautRubyEgg", "Wynaut" },
    [161] = { "WobbuffetRuby", "WobbuffetRubyEgg", "Wobbuffet" },
    [162] = { "NatuRubyEgg", "NatuSapphireEgg", "Natu" },
    [163] = { "XatuRubyEgg", "XatuSapphireEgg", "Xatu" },
    [164] = { "GirafarigRuby", "Girafarig" },
    [165] = { "PhanpyRubyEgg", "PhanpySapphireEgg", "Phanpy" },
    [166] = { "DonphanRubyEgg", "DonphanSapphireEgg", "Donphan" },
    [167] = { "PinsirRuby", "Pinsir" },
    [168] = { "HeracrossRuby", "Heracross" },
    [169] = { "RhyhornRuby", "Rhyhorn" },
    [170] = { "RhydonRuby", "Rhydon" },
    [171] = { "SnoruntRubyEgg", "SnoruntSapphireEgg", "Snorunt" },
    [172] = { "GlalieRubyEgg", "GlalieSapphireEgg", "Glalie" },
    [173] = { "SphealRubyEgg", "SphealSapphireEgg", "Spheal" },
    [174] = { "SealeoRubyEgg", "SealeoSapphireEgg", "Sealeo" },
    [175] = { "WalreinRubyEgg", "WalreinSapphireEgg", "Walrein" },
    [176] = { "ClamperlSapphire", "Clamperl" },
    [177] = { "HuntailSapphire", "Huntail" },
    [178] = { "GorebyssSapphire", "Gorebyss" },
    [179] = { "RelicanthSapphire", "RelicanthRuby", "Relicanth" },
    [180] = { "CorsolaRubyEgg", "CorsolaSapphireEgg", "Corsola" },
    [181] = { "ChinchouSapphireEgg", "Chinchou" },
    [182] = { "LanturnSapphireEgg", "Lanturn" },
    [183] = { "LuvdiscSapphire", "LuvdiscRuby", "Luvdisc" },
    [184] = { "HorseaRubyEgg", "HorseaSapphireEgg", "Horsea" },
    [185] = { "SeadraRubyEgg", "SeadraSapphireEgg", "Seadra" },
    [186] = { "KingdraRubyEgg", "KingdraSapphireEgg", "Kingdra" },
    [187] = { "BagonRubyEgg", "BagonSapphireEgg", "Bagon" },
    [188] = { "ShelgonSapphire", "ShelgonRuby", "ShelgonRubyEgg", "ShelgonSapphireEgg", "Shelgon" },
    [189] = { "SalamenceSapphire", "SalamenceRuby", "SalamenceRubyEgg", "SalamenceSapphireEgg", "Salamence" },
    [190] = { "BeldumSapphire", "BeldumRuby", "Beldum" },
    [191] = { "MetangSapphire", "MetangRuby", "Metang" },
    [192] = { "MetagrossSapphire", "MetagrossRuby", "Metagross" },
    [193] = { "RegirockSapphire", "RegirockRuby", "Regirock" },
    [194] = { "RegiceSapphire", "RegiceRuby", "Regice" },
    [195] = { "RegisteelSapphire", "RegisteelRuby", "Registeel" },
    [196] = { "LatiasSapphire", "Latias" },
    [197] = { "LatiosRuby", "Latios" },
    [198] = { "KyogreSapphire", "Kyogre" },
    [199] = { "GroudonRuby", "Groudon" },
    [200] = { "RayquazaSapphire", "RayquazaRuby", "Rayquaza" },
    [201] = { "JirachiSapphire", "JirachiRuby", "Jirachi" },
    [202] = { "ChikoritaRuby", "ChikoritaSapphire", "Chikorita" },
    [203] = { "CyndaquilRuby", "CyndaquilSapphire", "Cyndaquil" },
    [204] = { "TotodileRuby", "TotodileSapphire", "Totodile" },
    [205] = { "AerodactylRuby", "AerodactylSapphire", "Aerodactyl" },




}
